Repository leanprover-community/mathlib, pull requests merged in 2019-05, with the labels that each got.

#965 feat(script/auth_github): improve messages [ci skip]
  scripts/auth_github.py
Labels: ready-to-merge

#931 feat(category_theory/limits): complete lattices have (co)limits
  src/category_theory/limits/lattice.lean
Labels: ready-to-merge

#935 fix(tactic/library_search): iff lemmas with universes
  src/tactic/basic.lean
  src/tactic/library_search.lean
  test/library_search/basic.lean
  test/library_search/ordered_ring.lean
Labels: ready-to-merge

#926 feat(category_theory/limits/opposites): (co)limits in opposite categories
  src/category_theory/const.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/opposites.lean
  src/category_theory/opposites.lean
  src/category_theory/yoneda.lean
Labels: ready-to-merge

#951 feat(ring_theory/ideal_operations): inj_iff_trivial_ker for ring homomorphisms
  src/group_theory/subgroup.lean
  src/ring_theory/ideal_operations.lean
Labels: ready-to-merge

#968 fix(script/remote-install-update-mathlib)
  README.md
  scripts/remote-install-update-mathlib.sh
Labels: ready-to-merge

#969 fix(scripts/remote-install-update-mathlib): apt shouldn't ask
  scripts/remote-install-update-mathlib.sh
Labels: ready-to-merge

#971 fix(category_theory): remove duplication of unitors and associators for functors
  src/category_theory/natural_isomorphism.lean
Labels: ready-to-merge

#972 chore(docs): delete docs/wip.md
  README.md
  docs/wip.md
Labels: ready-to-merge

#938 feat(category_theory/limits): support for special shapes of (co)limits
  docs/tutorial/category_theory/calculating_colimits_in_Top.lean
  src/category_theory/discrete_category.lean
  src/category_theory/instances/Top/basic.lean
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/limits/shapes/default.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/products.lean
  src/category_theory/limits/shapes/pullbacks.lean
  src/category_theory/sparse.lean
  src/tactic/basic.lean
Labels: ready-to-merge

#974 Debian install
  docs/install_debian.md
  docs/install_debian_details.md
  scripts/install_debian.sh
Labels: ready-to-merge

#967 feat(tactic/decl_mk_const): performance improvement for library_search
  src/tactic/basic.lean
  src/tactic/library_search.lean
  test/fin_cases.lean
  test/library_search/basic.lean
  test/library_search/ordered_ring.lean
  test/library_search/ring_theory.lean
  test/mllist.lean
Labels: ready-to-merge

#977 feat(logic/basic): forall_iff_forall_surj
  src/logic/basic.lean
Labels: ready-to-merge

#979 fix(data/set/finite): make fintype_seq an instance
  src/data/set/finite.lean
Labels: ready-to-merge

#980 feat(data/set/basic): prod_subset_iff
  src/data/set/basic.lean
Labels: ready-to-merge

#886 feat(presheaves)
  src/algebraic_geometry/presheafed_space.lean
  src/category_theory/instances/Top/basic.lean
  src/category_theory/instances/Top/default.lean
  src/category_theory/instances/Top/open_nhds.lean
  src/category_theory/instances/Top/opens.lean
  src/category_theory/instances/Top/presheaf.lean
  src/category_theory/opposites.lean
Labels: ready-to-merge

#982 feat(category_theory/products): associators
  src/category_theory/products/associator.lean
  src/category_theory/products/bifunctor.lean
  src/category_theory/products/default.lean
Labels: ready-to-merge

#756 feat(ring_theory/adjoin): adjoining elements to form subalgebras
  src/ring_theory/adjoin.lean
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#987 six(style.md): fix broken code
  docs/style.md
Labels: ready-to-merge

#981 feat(category_theory): currying for functors
  src/category_theory/currying.lean
Labels: ready-to-merge

#989 Build with nightly
  .travis.yml
Labels: WIP

#733 feat(category/monad/cont): monad_cont instances for state_t, reader_t, except_t and option_t
  src/category/monad/basic.lean
  src/category/monad/cont.lean
  src/category/monad/writer.lean
Labels: ready-to-merge

#992 feat(scripts): add --build-new flag to cache-olean
  scripts/cache-olean.py
Labels: ready-to-merge

#835 building the hyperreal library
  src/algebra/ordered_group.lean
  src/data/real/basic.lean
  src/data/real/hyperreal.lean
  src/order/filter/basic.lean
  src/order/filter/filter_product.lean
Labels: ready-to-merge

#990 feat(category_theory/category_of_elements)
  src/category_theory/elements.lean
  src/category_theory/punit.lean
Labels: ready-to-merge

#994 feat(group_theory/subgroup): is_subgroup.inter
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
Labels: ready-to-merge

#996 feat(*): preorder instances for with_bot and with_zero
  src/algebra/ordered_group.lean
  src/order/bounded_lattice.lean
Labels: ready-to-merge

#995 refactor(order/basic): make type class args explicit in {*}order.lift
  src/algebra/ordered_group.lean
  src/data/fin.lean
  src/data/real/nnreal.lean
  src/linear_algebra/basic.lean
  src/order/basic.lean
  src/order/zorn.lean
Labels: ready-to-merge

#998 refactor(strict_mono): make definition + move to order_functions
  src/algebra/order.lean
  src/algebra/order_functions.lean
  src/ring_theory/noetherian.lean
  src/set_theory/ordinal.lean
Labels: ready-to-merge

#997 feat(algebra/pointwise): More lemmas on pointwise multiplication
  src/algebra/pointwise.lean
Labels: ready-to-merge

#963 feat(set_theory): add to cardinal, ordinal, cofinality
  src/data/equiv/basic.lean
  src/linear_algebra/dimension.lean
  src/linear_algebra/finsupp.lean
  src/measure_theory/measurable_space.lean
  src/order/basic.lean
  src/order/order_iso.lean
  src/set_theory/cardinal.lean
  src/set_theory/cofinality.lean
  src/set_theory/ordinal.lean
Labels: ready-to-merge

#1004 fix(tactic/basic): missing `conv` from tactic.basic
  src/tactic/basic.lean
Labels: ready-to-merge

#1008 fix(category/fold): use correct `opposite`
  src/category/fold.lean
  src/category_theory/opposites.lean
Labels: ready-to-merge

#1009 refactor(algebra/associated): rename nonzero_of_irreducible to ne_zero_of_irreducible
  src/algebra/associated.lean
  src/field_theory/splitting_field.lean
  src/ring_theory/principal_ideal_domain.lean
  src/ring_theory/unique_factorization_domain.lean
Labels: ready-to-merge

#1010 feat(data/polynomial): degree_eq_one_of_irreducible_of_root
  src/data/polynomial.lean
Labels: ready-to-merge

#993 feat(logic/function): comp₂ -- useful for binary operations
  src/category/bifunctor.lean
  src/category/bitraversable/instances.lean
  src/logic/function.lean
Labels: ready-to-merge

#1013 feat(topology/maps): closed embeddings
  src/topology/maps.lean
Labels: ready-to-merge

#1005 feat(category_theory): lemmas about cancellation
  src/category_theory/category.lean
Labels: ready-to-merge

#976 feat(Top.presheaf_ℂ): presheaves of functions to topological commutative rings
  src/category_theory/instances/CommRing/basic.lean
  src/category_theory/instances/Top/default.lean
  src/category_theory/instances/Top/opens.lean
  src/category_theory/instances/Top/presheaf_of_functions.lean
  src/category_theory/instances/TopCommRing/basic.lean
  src/category_theory/instances/TopCommRing/default.lean
Labels: ready-to-merge

#1001 feat(category_theory/iso): missing lemmas
  src/algebraic_geometry/presheafed_space.lean
  src/category_theory/category.lean
  src/category_theory/isomorphism.lean
Labels: ready-to-merge

#1003 feat(category_theory/products): missing simp lemmas
  src/category_theory/products/default.lean
Labels: ready-to-merge

#1014 feat(tactics/interactive): choose uses exists_prop
  src/tactic/interactive.lean
  src/topology/bounded_continuous_function.lean
  test/examples.lean
Labels: ready-to-merge

#1020 feat(data/equiv/basic): equiv.nonempty_iff_nonempty
  src/data/equiv/basic.lean
Labels: ready-to-merge

#1016 feat(topology/constructions): topology of sum types
  src/data/sigma/basic.lean
  src/topology/constructions.lean
  src/topology/maps.lean
  src/topology/order.lean
Labels: ready-to-merge

#1022 feat(algebra/order_functions): generalize strict_mono.monotone
  src/algebra/order_functions.lean
Labels: ready-to-merge

#1021 feat(category_theory/opposites): iso.op
  src/category_theory/opposites.lean
Labels: ready-to-merge

#1019 chore(*): using squeeze_simp
  src/algebra/group_power.lean
  src/algebra/pi_instances.lean
  src/category_theory/equivalence.lean
  src/category_theory/whiskering.lean
  src/category_theory/yoneda.lean
  src/data/fin.lean
  src/data/semiquot.lean
  src/data/set/intervals.lean
Labels: ready-to-merge

#966 feat(analysis/normed_space/deriv): more material on derivatives
  src/analysis/asymptotics.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/bounded_linear_maps.lean
  src/analysis/normed_space/deriv.lean
  src/analysis/normed_space/operator_norm.lean
  src/linear_algebra/basic.lean
  src/topology/constructions.lean
  src/topology/order.lean
Labels: ready-to-merge

#1027 fix(data/multiset): remove duplicate setoid instance
  src/data/list/perm.lean
  src/data/multiset.lean
Labels: ready-to-merge

#988 feat(tactic): new tactics to normalize casts inside expressions
  docs/tactics.md
  src/algebra/char_zero.lean
  src/algebra/group_power.lean
  src/data/complex/basic.lean
  src/data/int/basic.lean
  src/data/nat/cast.lean
  src/data/nat/enat.lean
  src/data/padics/padic_integers.lean
  src/data/padics/padic_norm.lean
  src/data/padics/padic_numbers.lean
  src/data/rat.lean
  src/ring_theory/multiplicity.lean
  src/tactic/norm_cast.lean
  test/norm_cast.lean
Labels: ready-to-merge

#1026 feat(data/equiv/functor): map_equiv
  src/data/equiv/functor.lean
Labels: ready-to-merge

#1031 feat(data/nat/basic): decreasing induction
  src/data/nat/basic.lean
Labels: ready-to-merge

#986 feat(category_theory): adjoint equivalences and limits under equivalences
  src/category_theory/adjunction.lean
  src/category_theory/category.lean
  src/category_theory/const.lean
  src/category_theory/currying.lean
  src/category_theory/discrete_category.lean
  src/category_theory/elements.lean
  src/category_theory/equivalence.lean
  src/category_theory/fully_faithful.lean
  src/category_theory/functor.lean
  src/category_theory/functor_category.lean
  src/category_theory/instances/CommRing/adjunctions.lean
  src/category_theory/instances/Top/adjunctions.lean
  src/category_theory/isomorphism.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/opposites.lean
  src/category_theory/limits/shapes/products.lean
  src/category_theory/natural_isomorphism.lean
  src/category_theory/natural_transformation.lean
  src/category_theory/products/associator.lean
  src/category_theory/products/default.lean
  src/category_theory/whiskering.lean
  src/category_theory/yoneda.lean
Labels: ready-to-merge

#984 feat(tactic/terminal_goal): determine if other goals depend on the current one
  src/tactic/core.lean
  test/terminal_goal.lean
Labels: ready-to-merge

#1034 refactor(topology): change continuous_at_within to continuous_within_at
  src/analysis/normed_space/deriv.lean
  src/topology/basic.lean
  src/topology/constructions.lean
  src/topology/order.lean
Labels: ready-to-merge

#1030 feat(category_theory): monos and epis in Type and Top
  src/category_theory/epi_mono.lean
  src/category_theory/instances/Top/default.lean
  src/category_theory/instances/Top/epi_mono.lean
  src/category_theory/types.lean
Labels: ready-to-merge

#1033 chore(*): reduce imports
  src/data/holor.lean
  src/order/filter/basic.lean
  src/order/filter/filter_product.lean
  src/order/filter/partial.lean
  src/topology/algebra/monoid.lean
Labels: ready-to-merge

#1037 fix(data/nat/enat): Fix typo in lemma name
  src/data/nat/enat.lean
Labels: ready-to-merge

#1032 feat(data/nat/basic): make decreasing induction eliminate to Sort
  src/data/nat/basic.lean
Labels: ready-to-merge

#1036 chore(opposites): merge two definitions of `opposite`
  src/algebra/opposites.lean
  src/category_theory/adjunction.lean
  src/category_theory/const.lean
  src/category_theory/discrete_category.lean
  src/category_theory/eq_to_hom.lean
  src/category_theory/instances/Top/open_nhds.lean
  src/category_theory/instances/Top/opens.lean
  src/category_theory/instances/Top/presheaf.lean
  src/category_theory/instances/Top/presheaf_of_functions.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/opposites.lean
  src/category_theory/opposites.lean
  src/category_theory/yoneda.lean
  src/data/opposite.lean
Labels: ready-to-merge

#1040 fix(data/complex/exponential): make complex.exp irreducible
  src/data/complex/exponential.lean
Labels: ready-to-merge

#1039 feat(tactic/basic): add tactic.rewrite, and sort list
  src/tactic/basic.lean
Labels: ready-to-merge

#1035 refactor: change variables order in some composition lemmas
  src/analysis/complex/exponential.lean
  src/analysis/complex/polynomial.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/deriv.lean
  src/category_theory/concrete_category.lean
  src/measure_theory/borel_space.lean
  src/measure_theory/giry_monad.lean
  src/measure_theory/integration.lean
  src/measure_theory/measurable_space.lean
  src/measure_theory/measure_space.lean
  src/topology/algebra/continuous_functions.lean
  src/topology/algebra/group.lean
  src/topology/algebra/group_completion.lean
  src/topology/algebra/monoid.lean
  src/topology/algebra/ring.lean
  src/topology/algebra/uniform_group.lean
  src/topology/algebra/uniform_ring.lean
  src/topology/basic.lean
  src/topology/bounded_continuous_function.lean
  src/topology/compact_open.lean
  src/topology/constructions.lean
  src/topology/instances/complex.lean
  src/topology/instances/ennreal.lean
  src/topology/instances/nnreal.lean
  src/topology/instances/real.lean
  src/topology/maps.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/completion.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/isometry.lean
  src/topology/uniform_space/completion.lean
Labels: ready-to-merge

#958 feat(set_theory/surreal): surreal numbers
  src/set_theory/surreal.lean
Labels: WIP, help wanted, ready-to-merge

#1042 fix(topology/stone_cech): faster proof from @PatrickMassot
  src/topology/stone_cech.lean
Labels: ready-to-merge

#1045 feat(category_theory/equivalence): make definition of adjointify_η easier to elaborate
  src/category_theory/equivalence.lean
Labels: ready-to-merge

#1041 refactor(data/complex/exponential): improve trig proofs
  src/algebra/group.lean
  src/algebra/group_power.lean
  src/algebra/ring.lean
  src/analysis/complex/exponential.lean
  src/data/complex/basic.lean
  src/data/complex/exponential.lean
Labels: ready-to-merge

#1043 feat(topology/order): make nhds irreducible
  src/topology/basic.lean
  src/topology/order.lean
Labels: ready-to-merge

#1052 refactor(topology/metric/gromov_hausdorff): make Hausdorff_edist irreducible
  src/topology/metric_space/hausdorff_distance.lean
Labels: ready-to-merge

#1055 refactor: coherent composition order
  src/analysis/asymptotics.lean
  src/analysis/complex/exponential.lean
  src/analysis/normed_space/banach.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/deriv.lean
  src/analysis/specific_limits.lean
  src/data/padics/hensel.lean
  src/measure_theory/borel_space.lean
  src/measure_theory/decomposition.lean
  src/order/filter/basic.lean
  src/topology/algebra/group.lean
  src/topology/algebra/group_completion.lean
  src/topology/algebra/infinite_sum.lean
  src/topology/algebra/monoid.lean
  src/topology/algebra/ordered.lean
  src/topology/algebra/uniform_group.lean
  src/topology/basic.lean
  src/topology/constructions.lean
  src/topology/instances/complex.lean
  src/topology/instances/ennreal.lean
  src/topology/instances/nnreal.lean
  src/topology/instances/real.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/completion.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/lipschitz.lean
  src/topology/order.lean
  src/topology/sequences.lean
  src/topology/uniform_space/basic.lean
  src/topology/uniform_space/completion.lean
  src/topology/uniform_space/separation.lean
Labels: ready-to-merge

#1056 feat(tactic/linarith): better input syntax linarith only [...]
  docs/tactics.md
  src/analysis/complex/exponential.lean
  src/data/complex/exponential.lean
  src/tactic/core.lean
  src/tactic/linarith.lean
  src/tactic/ring.lean
  test/linarith.lean
  test/ring.lean
Labels: ready-to-merge

#1061 feat(topology/opens): continuous.comap : opens Y → opens X
  src/topology/opens.lean
Labels: ready-to-merge

#1015 feat(tactic/basic): adds `contrapose` tactic
  docs/tactics.md
  src/tactic/basic.lean
  src/tactic/core.lean
  src/tactic/interactive.lean
  src/tactic/push_neg.lean
  test/push_neg.lean
Labels: ready-to-merge

#1062 chore(ring_theory/algebra): simp-lemmas for alg_hom.to_linear_map
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#1065 chore(topology/algebra/monoid): continuous_mul_left/right
  src/topology/algebra/monoid.lean
Labels: ready-to-merge

#1006 feat(category_theory): limits in CommRing
  src/algebra/pi_instances.lean
  src/category_theory/instances/CommRing/basic.lean
  src/category_theory/instances/CommRing/limits.lean
  src/category_theory/limits/types.lean
  src/category_theory/types.lean
Labels: ready-to-merge

#1066 feat(algebra/pi_instances): product of submonoids/groups/rings
  src/algebra/pi_instances.lean
Labels: ready-to-merge

#1072 refactor(integration.lean): changing `measure_space` to `measurable_s…
  src/measure_theory/integration.lean
Labels: ready-to-merge

#1069 feat(*): image_closure
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
  src/ring_theory/subring.lean
Labels: ready-to-merge

#1017 feat(data/nat): various lemmas
  src/data/nat/basic.lean
Labels: ready-to-merge

#1064 feat(linear_algebra/basic): general_linear_group basics
  src/linear_algebra/basic.lean
Labels: ready-to-merge

#1075 doc(finsupp,category_theory): fixes
  docs/theories/category_theory.md
  src/data/finsupp.lean
Labels: ready-to-merge

#1049 chore(CommRing/adjunctions): refactor proofs
  src/category_theory/adjunction/basic.lean
  src/category_theory/adjunction/default.lean
  src/category_theory/adjunction/limits.lean
  src/category_theory/epi_mono.lean
  src/category_theory/instances/CommRing/adjunctions.lean
  src/category_theory/instances/CommRing/basic.lean
  src/category_theory/instances/Top/adjunctions.lean
  src/category_theory/types.lean
  src/data/int/basic.lean
  src/data/mv_polynomial.lean
  src/tactic/tidy.lean
Labels: ready-to-merge

#1078 refactor(set_theory/ordinal): shorten proof of well_ordering_thm
  src/set_theory/ordinal.lean
Labels: ready-to-merge

#1029 feat(group_theory/conjugates) : define conjugates
  src/algebra/group.lean
  src/group_theory/subgroup.lean
Labels: ready-to-merge

#1094 feat(ordered_group): add missing instance
  src/algebra/ordered_group.lean
Labels: ready-to-merge

#1018 feat(presheaves/stalks): stalks of presheafs, and presheafed spaces with extra structure on stalks
  src/algebraic_geometry/presheafed_space.lean
  src/algebraic_geometry/stalks.lean
  src/category_theory/functor_category.lean
  src/category_theory/instances/Top/basic.lean
  src/category_theory/instances/Top/open_nhds.lean
  src/category_theory/instances/Top/opens.lean
  src/category_theory/instances/Top/presheaf.lean
  src/category_theory/instances/Top/presheaf_of_functions.lean
  src/category_theory/instances/Top/stalks.lean
  src/category_theory/instances/TopCommRing/basic.lean
  src/category_theory/limits/functor_category.lean
  src/category_theory/natural_isomorphism.lean
  src/category_theory/natural_transformation.lean
  src/category_theory/whiskering.lean
  src/data/opposite.lean
Labels: ready-to-merge

#734 feat(ring_theory): free_ring and free_comm_ring
  src/group_theory/free_abelian_group.lean
  src/ring_theory/free_comm_ring.lean
  src/ring_theory/free_ring.lean
Labels: ready-to-merge

#1002 feat(category_theory/monoidal): monoidal categories, monoidal functors
  src/category_theory/monoidal/category.lean
  src/category_theory/monoidal/category_aux.lean
  src/category_theory/monoidal/functor.lean
Labels: ready-to-merge

#1100 feat(category_theory/monoidal): the monoidal category of types
  src/category_theory/monoidal/types.lean
Labels: ready-to-merge

#1054 fix(data/nat/enat): change [] to {} in some lemmas
  src/data/nat/enat.lean
Labels: ready-to-merge

#1067 feat(topology/algebra/open_subgroup): basics on open subgroups
  src/topology/algebra/open_subgroup.lean
Labels: ready-to-merge
