Repository leanprover-community/mathlib, pull requests merged in 2019-10, with the labels that each got.

#1493 chore(linear_map): use curly brackets for type class in linear_map coe_to_fun
  src/algebra/module.lean
  src/field_theory/mv_polynomial.lean
Labels: ready-to-merge

#1483 feat(tactic/delta_instance): handle parameters and use in library
  src/category_theory/comma.lean
  src/data/nat/modeq.lean
  src/data/rel.lean
  src/field_theory/mv_polynomial.lean
  src/linear_algebra/dual.lean
  src/tactic/core.lean
  src/topology/uniform_space/compare_reals.lean
  test/delta_instance.lean
Labels: ready-to-merge

#1502 fix(dioph): remove global vector3 notation
  src/number_theory/dioph.lean
Labels: ready-to-merge

#1141 feat(data/equiv/algebra): automorphism groups for other structures
  src/data/equiv/algebra.lean
Labels: ready-to-merge

#1499 chore(*): fix errors in library and sanity_check
  src/algebra/big_operators.lean
  src/algebra/order_functions.lean
  src/analysis/complex/exponential.lean
  src/category/functor.lean
  src/category_theory/isomorphism.lean
  src/category_theory/limits/preserves.lean
  src/computability/turing_machine.lean
  src/data/finset.lean
  src/data/finsupp.lean
  src/data/fintype.lean
  src/data/list/basic.lean
  src/data/list/defs.lean
  src/data/opposite.lean
  src/data/rat/order.lean
  src/data/seq/computation.lean
  src/data/set/finite.lean
  src/data/set/function.lean
  src/logic/basic.lean
  src/meta/expr.lean
  src/meta/rb_map.lean
  src/set_theory/ordinal.lean
  src/tactic/core.lean
  src/tactic/interactive.lean
  src/tactic/sanity_check.lean
  src/topology/category/Top/open_nhds.lean
  test/sanity_check.lean
Labels: ready-to-merge

#1498 feat(tactic/squeeze_simp): better handling of private declarations
  src/tactic/core.lean
Labels: ready-to-merge

#1501 doc(linear_algebra/basic): add module and declaration doc strings
  src/linear_algebra/basic.lean
Labels: ready-to-merge

#1089 feat(algebra): commuting elements
  src/algebra/big_operators.lean
  src/algebra/commute.lean
  src/algebra/geom_sum.lean
  src/algebra/group_power.lean
  src/analysis/specific_limits.lean
  src/data/complex/exponential.lean
  src/data/nat/choose.lean
  src/data/set/lattice.lean
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
  src/ring_theory/subring.lean
Labels: ready-to-merge

#1420 feat(algebra/Module): the category of R-modules
  src/algebra/category/Module/basic.lean
  src/algebra/punit_instances.lean
Labels: ready-to-merge

#1504 fix(data/list/min_max): docs typo
  src/data/list/min_max.lean
Labels: ready-to-merge

#1508 feat(algebra/opposites): add some trivial `@[simp]` lemmas
  src/algebra/opposites.lean
Labels: ready-to-merge

#1510 chore(topology): sanity_check pass
  src/topology/algebra/open_subgroup.lean
  src/topology/algebra/uniform_ring.lean
  src/topology/constructions.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/isometry.lean
  src/topology/stone_cech.lean
  src/topology/uniform_space/separation.lean
Labels: ready-to-merge

#1511 feat(group_theory/submonoid): define `subtype.comm_monoid`
  src/group_theory/submonoid.lean
Labels: ready-to-merge

#1513 refactor(topology/maps): avoid repetition in dense embeddings
  src/topology/maps.lean
Labels: ready-to-merge

#1514 refactor(topology/list): move topology of lists, vectors to new file
  src/topology/constructions.lean
  src/topology/list.lean
  src/topology/order.lean
Labels: ready-to-merge

#1505 doc(topology/order): module and definition docstrings
  src/topology/basic.lean
  src/topology/order.lean
Labels: ready-to-merge

#1515 refactor(topology/dense_embedding): move dense embeddings to new file
  src/topology/constructions.lean
  src/topology/dense_embedding.lean
  src/topology/maps.lean
Labels: ready-to-merge

#1518 chore(topology/algebra/group_completion): missing namespace
  src/topology/algebra/group_completion.lean
Labels: ready-to-merge

#1507 feat(data/quot): define `quotient.map₂'`, use it for group quotient
  src/data/quot.lean
  src/group_theory/quotient_group.lean
Labels: ready-to-merge

#1512 feat(tactic/find): find defs as well as theorems
  src/tactic/find.lean
Labels: ready-to-merge

#1516 refactor(topology/continuous_on): move continuous_{on,within_at} to own file
  src/topology/algebra/monoid.lean
  src/topology/basic.lean
  src/topology/constructions.lean
  src/topology/continuous_on.lean
  src/topology/local_homeomorph.lean
  src/topology/order.lean
Labels: ready-to-merge

#1503 doc(linear_algebra/basis): add doc
  src/linear_algebra/basis.lean
Labels: ready-to-merge

#1522 feat(algebra/ordered...): Two tiny lemmas
  src/algebra/floor.lean
  src/algebra/ordered_field.lean
Labels: ready-to-merge

#1527 refactor(topology/algebra/polynomial): move topology.instances.polynomial
  src/analysis/complex/polynomial.lean
  src/data/padics/hensel.lean
  src/topology/algebra/polynomial.lean
Labels: ready-to-merge

#1520 fix(tactic/{use,ring}): instantiate metavariables in goal
  src/tactic/core.lean
  src/tactic/ring.lean
Labels: ready-to-merge

#1530 chore(ring_theory/adjoin_root): remove some unused decidable_eq
  src/ring_theory/adjoin_root.lean
Labels: ready-to-merge

#1521 chore(linear_algebra): rename type variables
  src/linear_algebra/basic.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/bilinear_form.lean
  src/linear_algebra/dimension.lean
  src/linear_algebra/direct_sum_module.lean
  src/linear_algebra/finsupp.lean
  src/linear_algebra/finsupp_vector_space.lean
  src/linear_algebra/matrix.lean
  src/linear_algebra/sesquilinear_form.lean
  src/linear_algebra/tensor_product.lean
Labels: ready-to-merge

#1523 chore(algebra/module): use curly brackets instead of square brackets in more places
  src/algebra/module.lean
Labels: ready-to-merge

#1524 chore(algebra/group/hom): use curly brackets for instances where possible
  src/algebra/group/hom.lean
Labels: ready-to-merge

#1537 fix(algebra/char_p): typo in docstring
  src/algebra/char_p.lean
Labels: ready-to-merge

#1532 refactor(ring_theory/algebra): algebra should extend has_scalar not module
  src/ring_theory/algebra.lean
  src/ring_theory/ideal_operations.lean
  src/ring_theory/integral_closure.lean
Labels: ready-to-merge

#1525 chore(algebra/ring): use curly brackets for ring_hom where possible
  src/algebra/ring.lean
Labels: ready-to-merge

#1529 refactor(ring_theory/algebra): alg_hom extends ring_hom and use curly brackets
  src/algebra/ring.lean
  src/ring_theory/algebra.lean
Labels: ready-to-merge, request-review

#1538 minor updates to the installation instructions
  docs/install/linux.md
  docs/install/macos.md
  docs/install/windows.md
Labels: ready-to-merge

#1543 fix(topology/algebra/group_completion): remove redundant instance parameters
  src/topology/algebra/group_completion.lean
Labels: ready-to-merge

#1542 fix(topology/continuous_on): avoid duplicate instance arguments
  src/topology/continuous_on.lean
Labels: ready-to-merge

#1541 refactor(topology): mild reorganization
  docs/theories.md
  docs/theories/topology.md
  src/topology/algebra/group.lean
  src/topology/bases.lean
  src/topology/basic.lean
  src/topology/compact_open.lean
  src/topology/constructions.lean
  src/topology/dense_embedding.lean
  src/topology/homeomorph.lean
  src/topology/local_homeomorph.lean
  src/topology/maps.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/opens.lean
  src/topology/order.lean
  src/topology/separation.lean
  src/topology/stone_cech.lean
  src/topology/subset_properties.lean
  src/topology/uniform_space/basic.lean
  src/topology/uniform_space/complete_separated.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#1545 feat(data/int/basic): int.nat_abs_eq_zero
  src/data/int/basic.lean
Labels: ready-to-merge

#1544 docs(topology): some more module docstrings
  src/topology/constructions.lean
  src/topology/maps.lean
  src/topology/order.lean
Labels: ready-to-merge

#1547 fix(doc/contribute): fix broken link [ci skip]
  docs/contribute/doc.md
Labels: ready-to-merge

#1546 feat(data/polynomial): card_roots'
  src/data/polynomial.lean
Labels: ready-to-merge

#1548 feat(data/zmod/basic): val_min_abs
  src/data/zmod/basic.lean
Labels: ready-to-merge

#1455 archive(imo1988_q6): a formalization of Q6 on IMO1988
  archive/imo1988_q6.lean
Labels: ready-to-merge

#1519 feat(ring_theory/algebraic): algebraic extensions, algebraic elements
  src/data/polynomial.lean
  src/field_theory/minimal_polynomial.lean
  src/ring_theory/algebraic.lean
  src/ring_theory/integral_closure.lean
Labels: ready-to-merge, request-review

#1551 fix(topology/metric_space): fix uniform structure on Pi types
  src/data/finset.lean
  src/order/filter/basic.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/emetric_space.lean
Labels: ready-to-merge

#1549 refactor(topology,calculus): change subset condition for composition
  src/analysis/calculus/deriv.lean
  src/analysis/calculus/mean_value.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/calculus/times_cont_diff.lean
  src/data/equiv/local_equiv.lean
  src/data/set/basic.lean
  src/geometry/manifold/manifold.lean
  src/topology/algebra/ordered.lean
  src/topology/continuous_on.lean
  src/topology/local_homeomorph.lean
Labels: ready-to-merge

#1506 feat(category_theory): def `is_isomorphic_setoid`, `groupoid.iso_equiv_hom`
  src/category_theory/groupoid.lean
  src/category_theory/isomorphism_classes.lean
Labels: ready-to-merge

#1500 chore(category_theory): using simps
  src/category_theory/limits/cones.lean
  src/category_theory/limits/functor_category.lean
  src/category_theory/limits/over.lean
  src/category_theory/monad/adjunction.lean
  src/category_theory/monad/algebra.lean
  src/category_theory/monad/limits.lean
  src/category_theory/monoidal/functor.lean
  src/category_theory/whiskering.lean
  src/category_theory/yoneda.lean
Labels: ready-to-merge

#1568 feat(algebra/floor): prove `⌈x⌉ ≤ ⌊x⌋ + 1`
  src/algebra/floor.lean
Labels: ready-to-merge

#1556 feat(tactic/lint): rename and refactor sanity_check
  docs/tactics.md
  src/category/functor.lean
  src/measure_theory/l1_space.lean
  src/meta/rb_map.lean
  src/tactic/basic.lean
  src/tactic/core.lean
  src/tactic/doc_blame.lean
  src/tactic/interactive.lean
  src/tactic/lint.lean
  src/tactic/sanity_check.lean
  test/lint.lean
Labels: ready-to-merge

#1567 feat(algebra/big_operators): products and sums over `finset.Ico`
  src/algebra/big_operators.lean
  src/data/finset.lean
Labels: ready-to-merge

#1552 feat(tactic/suggest): generalize and reimplement library_search
  docs/tactics.md
  src/category/basic.lean
  src/data/list/defs.lean
  src/data/mllist.lean
  src/data/option/basic.lean
  src/data/option/defs.lean
  src/tactic/basic.lean
  src/tactic/core.lean
  src/tactic/library_search.lean
  src/tactic/rewrite_all/congr.lean
  src/tactic/suggest.lean
  test/library_search/basic.lean
  test/library_search/ordered_ring.lean
  test/library_search/ring_theory.lean
  test/mllist.lean
  test/suggest.lean
Labels: ready-to-merge

#1571 chore(meta/rb_map,tactic/monotonicity): replace rb_map.insert_cons
  src/meta/rb_map.lean
  src/tactic/monotonicity/basic.lean
Labels: ready-to-merge, request-review

#1575 fix(scripts): sanity_check -> lint [ci skip]
  .gitignore
  scripts/mk_all.sh
  scripts/rm_all.sh
Labels: ready-to-merge

#1574 feat(data/finset): define `finset.Ico.subset_iff`
  src/data/finset.lean
  src/data/nat/basic.lean
Labels: ready-to-merge

#1555 feat(geometric/manifold): smooth manifolds
  src/geometry/manifold/smooth_manifold_with_corners.lean
Labels: ready-to-merge

#1581 fix(algebra/group/hom): Fix extraneous arguments
  src/algebra/group/hom.lean
Labels: ready-to-merge

#1550 feat(*): various lemmas from the sensitivity project
  src/algebra/module.lean
  src/algebra/ring.lean
  src/data/set/finite.lean
  src/linear_algebra/dual.lean
  src/linear_algebra/finite_dimensional.lean
  src/linear_algebra/finsupp.lean
  src/ring_theory/power_series.lean
  src/set_theory/cardinal.lean
Labels: ready-to-merge

#1578 feat(data/finset): inj_on_of_surj_on_of_card_le
  src/data/finset.lean
Labels: ready-to-merge

#1491 refactor(category_theory,algebra/category): make algebraic categories not [reducible]
  src/algebra/category/CommRing/basic.lean
  src/algebra/category/CommRing/colimits.lean
  src/algebra/category/CommRing/limits.lean
  src/algebra/category/Group.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/category/Mon/colimits.lean
  src/category_theory/concrete_category/basic.lean
  src/category_theory/concrete_category/bundled.lean
  src/category_theory/concrete_category/bundled_hom.lean
  src/category_theory/full_subcategory.lean
  src/category_theory/limits/cones.lean
Labels: ready-to-merge

#1579 feat(data/nat/basic): division inequalities
  src/data/nat/basic.lean
Labels: ready-to-merge

#1558 feat(category_theory): add `reassoc` annotations
  docs/tactics.md
  src/category_theory/comma.lean
  src/category_theory/functor.lean
  src/tactic/reassoc_axiom.lean
  test/tactics.lean
Labels: ready-to-merge

#1588 chore(algebra/category/*/colimits): remove unnecessary projections
  src/algebra/category/CommRing/colimits.lean
  src/algebra/category/Mon/colimits.lean
Labels: ready-to-merge

#1553 feat(archive): add proof of sensitivity conjecture
  archive/sensitivity.lean
Labels: ready-to-merge

#1569 feat(algebra/group): conversion between `→*` and `→+`
  src/algebra/group/type_tags.lean
Labels: ready-to-merge

#1584 chore(algebra/category/CommRing/limits): fix typo, remove private
  src/algebra/category/CommRing/limits.lean
Labels: ready-to-merge

#1583 refactor(data/finset): restate disjoint_filter
  src/algebra/big_operators.lean
  src/data/finset.lean
  src/data/nat/totient.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/group_theory/order_of_element.lean
Labels: ready-to-merge

#1586 fix(category_theory/adjunctions): fix deterministic timeouts
  src/category_theory/adjunction/basic.lean
  src/category_theory/adjunction/limits.lean
  src/category_theory/limits/cones.lean
Labels: ready-to-merge

#1570 feat(analysis/normed_space): norms on ℤ and ℚ
  src/analysis/normed_space/basic.lean
  src/topology/instances/real.lean
Labels: ready-to-merge

#1585 chore(src/data/mv_polynomial): doc comments and removing unused arguments
  src/data/mv_polynomial.lean
Labels: ready-to-merge

#1592 fix(suggest): focus1 at the correct moment
  src/tactic/suggest.lean
  test/suggest.lean
Labels: ready-to-merge

#1597 feat(data/nat/modeq): div_mod_eq_mod_mul_div
  src/data/nat/modeq.lean
Labels: ready-to-merge

#1594 doc(topology/topological_fiber_bundle): documentation improvements
  src/topology/topological_fiber_bundle.lean
Labels: ready-to-merge

#1598 feat(algebra/big_operators): sum_ite
  src/algebra/big_operators.lean
Labels: ready-to-merge

#1593 feat(geometry/manifold): improvements for smooth manifolds
  src/analysis/calculus/times_cont_diff.lean
  src/geometry/manifold/manifold.lean
  src/geometry/manifold/real_instances.lean
  src/geometry/manifold/smooth_manifold_with_corners.lean
  src/linear_algebra/finite_dimensional.lean
Labels: ready-to-merge

#1576 feat(algebra/semiconj): define `semiconj_by` and some operations
  src/algebra/commute.lean
  src/algebra/semiconj.lean
Labels: ready-to-merge

#1590 feat(data/multiset): map_eq_map_of_bij_of_nodup
  src/algebra/big_operators.lean
  src/data/multiset.lean
Labels: ready-to-merge

#1599 chore(*): pass dup_namespace and def_lemma lint tests
  src/group_theory/free_group.lean
  src/linear_algebra/finite_dimensional.lean
  src/number_theory/pell.lean
  src/order/lattice.lean
  src/order/zorn.lean
  src/ring_theory/algebraic.lean
  src/set_theory/ordinal.lean
  src/tactic/reassoc_axiom.lean
  src/tactic/transfer.lean
Labels: ready-to-merge

#1591 fix(tactic/solve_by_elim): parameter parsing
  src/tactic/solve_by_elim.lean
  src/tactic/suggest.lean
  test/solve_by_elim.lean
  test/suggest.lean
Labels: ready-to-merge

#1604 chore(group_theory/free_group,order/zorn): rename zorn.zorn and sum.sum
  src/group_theory/free_group.lean
  src/order/filter/basic.lean
  src/order/zorn.lean
Labels: ready-to-merge

#1605 chore(category_theory): replace some @[simp] with @[simps]
  src/category_theory/limits/shapes/binary_products.lean
Labels: ready-to-merge

#1565 feat(meta/expr,data/rat/basic): add rat.reflect
  src/data/rat/default.lean
  src/data/rat/meta.lean
  src/meta/expr.lean
  src/tactic/norm_num.lean
  test/rat.lean
Labels: ready-to-merge

#1610 chore(data/nat/basic): remove pos_iff_ne_zero'
  src/analysis/complex/exponential.lean
  src/data/nat/basic.lean
  src/ring_theory/multiplicity.lean
Labels: ready-to-merge

#1612 refactor(data/rat/meta): rename to meta_defs
  src/data/rat/default.lean
  src/data/rat/meta_defs.lean
  src/tactic/norm_num.lean
  test/rat.lean
Labels: ready-to-merge

#1602 feat(data/set/intervals): fintype instances for ℕ and ℤ
  src/data/finset.lean
  src/data/fintype/intervals.lean
  src/data/int/basic.lean
Labels: ready-to-merge, request-review

#1603 feat(data/nat): a lemma about min_fac
  src/data/nat/basic.lean
  src/data/nat/prime.lean
Labels: ready-to-merge

#1595 feat(linear_algebra/basis): Dedekind's linear independence of characters
  src/data/finset.lean
  src/linear_algebra/basis.lean
Labels: ready-to-merge

#1614 chore(category_theory): remove superfluous lemma
  src/category_theory/category/default.lean
  src/category_theory/equivalence.lean
  src/category_theory/functor_category.lean
  src/category_theory/limits/limits.lean
Labels: ready-to-merge

#1621 fix(data/mv_polynomial): generalize equivs to comm_semiring
  src/data/mv_polynomial.lean
Labels: ready-to-merge

#1618 feat(linear_algebra/basic): define algebra structure on endomorphisms of module
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#1620 fix(tactic/omega): fix omega bugs, add docstring (closes #1484)
  src/tactic/omega/int/main.lean
  src/tactic/omega/main.lean
  src/tactic/omega/nat/main.lean
  test/omega.lean
Labels: ready-to-merge

#1624 chore(ring_theory/algebra): add docstring to algebra.comap and remove unused instances
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#1580 feat(tactic/lint): silent linting
  docs/tactics.md
  src/tactic/lint.lean
  test/lint.lean
Labels: ready-to-merge

#1611 feat(tactic/rcases): transport the `cases h : e` syntax to `rcases`
  docs/tactics.md
  src/tactic/lift.lean
  src/tactic/rcases.lean
  test/rcases.lean
Labels: ready-to-merge

#1627 fix(*): use has_coe_t
  src/data/seq/computation.lean
  src/group_theory/coset.lean
  src/order/filter/filter_product.lean
  src/ring_theory/localization.lean
  src/topology/uniform_space/completion.lean
Labels: ready-to-merge, request-review

#1628 feat(rat): give Q-algebra structure on field
  src/data/rat/cast.lean
  src/ring_theory/algebra.lean
Labels: ready-to-merge, request-review

#1629 cleanup(order|string)
  src/data/multiset.lean
  src/data/string/basic.lean
  src/order/basic.lean
  src/order/pilex.lean
  src/tactic/subtype_instance.lean
Labels: ready-to-merge

#1616 chore(category_theory): speed-up monoidal.of_has_finite_products
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/monoidal/of_has_finite_products.lean
Labels: ready-to-merge

#1560 feat(number_theory/sum_four_squares): every natural number is the sum of four square numbers
  src/algebra/big_operators.lean
  src/data/int/basic.lean
  src/data/int/parity.lean
  src/data/nat/cast.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/field_theory/finite.lean
  src/number_theory/sum_four_squares.lean
Labels: ready-to-merge

#1635 feat(data/fintype): fintype.card_subtype_lt
  src/data/fintype.lean
Labels: ready-to-merge

#1606 feat(.travis): add linting to CI
  .travis.yml
  scripts/mk_all.sh
Labels: RFC, ready-to-merge

#1626 feat(tactic/simps): allow let-expressions
  docs/tactics.md
  src/meta/expr.lean
  src/tactic/simps.lean
  test/simps.lean
Labels: ready-to-merge

#1633 feat(order/conditionally_complete_lattice): add complete_linear_order instance for enat
  src/data/nat/enat.lean
  src/order/conditionally_complete_lattice.lean
Labels: ready-to-merge

#1615 chore(data/set/finite): move defns up hierarchy; rename fintype_of_finset, card_fintype_of_finset
  src/data/finsupp.lean
  src/data/fintype.lean
  src/data/fintype/intervals.lean
  src/data/set/finite.lean
  src/group_theory/order_of_element.lean
Labels: ready-to-merge

#1613 chore(category_theory/whiskering): clean up
  src/algebraic_geometry/stalks.lean
  src/category_theory/monad/limits.lean
  src/category_theory/opposites.lean
  src/category_theory/whiskering.lean
  src/topology/sheaves/stalks.lean
Labels: ready-to-merge
