Repository leanprover-community/mathlib, pull requests merged in 2019-09, with the labels that each got.

#1378 chore(category_theory/notation): consistently use notation for functor.id
  src/category_theory/adjunction/basic.lean
  src/category_theory/comma.lean
  src/category_theory/equivalence.lean
  src/category_theory/fully_faithful.lean
  src/category_theory/functor.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/preserves.lean
  src/category_theory/monad/adjunction.lean
  src/category_theory/monad/basic.lean
  src/category_theory/monoidal/category.lean
  src/category_theory/monoidal/functor.lean
  src/category_theory/natural_isomorphism.lean
  src/category_theory/products/default.lean
  src/category_theory/whiskering.lean
  src/category_theory/yoneda.lean
  src/topology/Top/opens.lean
Labels: ready-to-merge

#1382 feat(data/nat/gcd): add simple lemmas
  src/data/nat/gcd.lean
Labels: ready-to-merge

#1386 chore(data/nat/gcd): remove pointless parentheses
  src/data/nat/gcd.lean
Labels: ready-to-merge

#1362 feat(category_theory/limits): construct limits from products and equalizers
  src/category_theory/const.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/limits/shapes/constructions/finite_products.lean
  src/category_theory/limits/shapes/constructions/limits_of_products_and_equalizers.lean
  src/category_theory/limits/shapes/constructions/pullbacks.lean
  src/category_theory/limits/shapes/constructions/sums.lean
Labels: ready-to-merge

#1381 feat(category_theory): define `iso.conj` and friends
  src/category_theory/conj.lean
Labels: ready-to-merge

#1390 fix(restate_axiom): create lemmas from lemmas
  src/tactic/restate_axiom.lean
Labels: ready-to-merge

#1374 feat(topology/uniform_space): Abstract completions
  src/topology/algebra/group_completion.lean
  src/topology/algebra/uniform_ring.lean
  src/topology/maps.lean
  src/topology/uniform_space/absolute_value.lean
  src/topology/uniform_space/abstract_completion.lean
  src/topology/uniform_space/compare_reals.lean
  src/topology/uniform_space/completion.lean
Labels: ready-to-merge

#1384 feat(data/equiv/basic): add more functions for equivalences between complex types
  src/data/equiv/basic.lean
  src/group_theory/coset.lean
  src/group_theory/sylow.lean
  src/set_theory/cardinal.lean
  src/set_theory/cofinality.lean
Labels: ready-to-merge

#1392 chore(linear_algebra/determinant): simplify det_mul proof
  src/linear_algebra/determinant.lean
Labels: ready-to-merge

#1394 perf(data/gaussian_int): speed up div and mod
  src/data/zsqrtd/gaussian_int.lean
Labels: ready-to-merge

#1259 feat(measure_theory): prove that the Giry monad is a monad in the category_theory sense
  src/measure_theory/Meas.lean
  src/measure_theory/giry_monad.lean
  src/measure_theory/measurable_space.lean
Labels: ready-to-merge

#1395 feat(tactic/doc_blame): Use is_auto_generated
  src/tactic/doc_blame.lean
Labels: ready-to-merge

#1357 feat(category_theory/sums): sums (disjoint unions) of categories
  src/category_theory/hom_functor.lean
  src/category_theory/limits/functor_category.lean
  src/category_theory/monoidal/category.lean
  src/category_theory/opposites.lean
  src/category_theory/products/associator.lean
  src/category_theory/products/basic.lean
  src/category_theory/products/bifunctor.lean
  src/category_theory/products/default.lean
  src/category_theory/sums/associator.lean
  src/category_theory/sums/basic.lean
  src/category_theory/sums/default.lean
  src/category_theory/yoneda.lean
Labels: ready-to-merge

#1340 feat(category_theory): finite products give a monoidal structure
  src/category_theory/limits/limits.lean
  src/category_theory/limits/shapes/constructions/finite_limits.lean
  src/category_theory/limits/shapes/constructions/limits.lean
  src/category_theory/monoidal/of_has_finite_products.lean
  src/category_theory/monoidal/types.lean
Labels: ready-to-merge

#1375 feat(order): add lemma
  src/algebra/order.lean
Labels: ready-to-merge

#1396 fix(topology/uniform_space): simplify continuity proof
  src/topology/uniform_space/basic.lean
Labels: ready-to-merge

#1397 feat(logic/basic): exists_eq'
  src/logic/basic.lean
Labels: ready-to-merge

#1387 fix(tactic/norm_num): bugfix bad proof application
  src/tactic/norm_num.lean
  test/norm_num.lean
Labels: ready-to-merge

#1359 feat(data/equiv/local_equiv): define local equivalences
  src/data/equiv/local_equiv.lean
Labels: ready-to-merge

#1366 feat(bounded_lattice/has_lt): add a `lt` relation independent from `l…
  src/algebra/ordered_group.lean
  src/order/bounded_lattice.lean
Labels: ready-to-merge

#1399 chore(order/filter): rephrase filter.has_le
  src/order/filter/basic.lean
  src/order/filter/lift.lean
  src/topology/basic.lean
Labels: ready-to-merge

#1400 chore(algebra/ordered_field): add simp attributes to inv_pos' and others
  src/algebra/ordered_field.lean
Labels: ready-to-merge

#1401 fix(naming): typo [ci skip]
  docs/contribute/naming.md
Labels: ready-to-merge

#1391 chore(data/mv_polynomial): use classical logic
  src/algebra/CommRing/adjunctions.lean
  src/data/finsupp.lean
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/field_theory/mv_polynomial.lean
  src/field_theory/splitting_field.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/dimension.lean
  src/linear_algebra/dual.lean
  src/linear_algebra/finsupp.lean
  src/linear_algebra/finsupp_vector_space.lean
  src/linear_algebra/matrix.lean
  src/ring_theory/adjoin_root.lean
  src/ring_theory/algebra.lean
  src/ring_theory/free_comm_ring.lean
  src/ring_theory/integral_closure.lean
  src/ring_theory/polynomial.lean
  src/ring_theory/power_series.lean
Labels: WIP

#1406 fix(category_theory/limits/shapes): doc typo [ci skip]
  src/category_theory/limits/shapes/binary_products.lean
Labels: ready-to-merge

#1405 refactor(category_theory/limits): make is_[co]limit not a class
  src/category_theory/adjunction/limits.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/preserves.lean
  src/category_theory/limits/shapes/terminal.lean
Labels: ready-to-merge

#1407 refactor(category_theory/limits/shapes/pullbacks): proof golf
  src/category_theory/limits/shapes/pullbacks.lean
Labels: WIP, ready-to-merge

#1059 feat(topology/constructions): distributivity of products over sums
  src/data/equiv/basic.lean
  src/data/set/lattice.lean
  src/topology/constructions.lean
  src/topology/maps.lean
Labels: ready-to-merge

#1398 feat(topology/local_homeomorph): local homeomorphisms
  src/topology/local_homeomorph.lean
Labels: ready-to-merge

#1415 feat(data/list/defs): move list.sum to list/defs.lean
  src/data/list/basic.lean
  src/data/list/defs.lean
Labels: ready-to-merge

#1414 feat(data/list/basic): make chain.nil a simp lemma
  src/data/list/basic.lean
  src/data/list/defs.lean
Labels: ready-to-merge

#1372 feat(algebra/floor): Split floor from archimedean file.
  src/algebra/archimedean.lean
  src/algebra/floor.lean
  src/data/rat/floor.lean
  src/tactic/norm_num.lean
Labels: ready-to-merge

#1424 feat(algebra/big_operators): sum_eq_zero_iff_of_nonpos
  src/algebra/big_operators.lean
  src/algebra/ordered_group.lean
Labels: ready-to-merge

#1389 feat(sanity_check): greatly improve performance
  src/data/bool.lean
  src/data/list/defs.lean
  src/meta/expr.lean
  src/tactic/core.lean
  src/tactic/sanity_check.lean
  test/sanity_check.lean
Labels: ready-to-merge

#1416 chore(topology): sanity_check pass
  src/analysis/asymptotics.lean
  src/analysis/convex.lean
  src/analysis/normed_space/bounded_linear_maps.lean
  src/analysis/normed_space/operator_norm.lean
  src/logic/basic.lean
  src/meta/rb_map.lean
  src/order/basic.lean
  src/order/bounded_lattice.lean
  src/order/complete_lattice.lean
  src/order/conditionally_complete_lattice.lean
  src/order/filter/partial.lean
  src/order/liminf_limsup.lean
  src/order/order_iso.lean
  src/topology/algebra/group.lean
  src/topology/algebra/infinite_sum.lean
  src/topology/algebra/module.lean
  src/topology/algebra/monoid.lean
  src/topology/algebra/ordered.lean
  src/topology/algebra/ring.lean
  src/topology/algebra/uniform_group.lean
  src/topology/bases.lean
  src/topology/basic.lean
  src/topology/constructions.lean
  src/topology/maps.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/cau_seq_filter.lean
  src/topology/metric_space/closeds.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/gluing.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/isometry.lean
  src/topology/opens.lean
  src/topology/order.lean
  src/topology/separation.lean
  src/topology/subset_properties.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#1388 feat(algebra/group/units): add some lemmas about `divp`
  src/algebra/group/units.lean
Labels: ready-to-merge

#1418 feat(algebra/order): allow simp to flip inequalities
  src/algebra/order.lean
  src/data/rat/order.lean
  src/number_theory/pell.lean
  src/tactic/linarith.lean
Labels: ready-to-merge

#1423 feat(tactic/{abel,ring}): state conditions of tactics more precisely
  docs/tactics.md
  src/tactic/abel.lean
  src/tactic/ring.lean
  test/abel.lean
Labels: ready-to-merge

#1428 feat(tactic/auto_cases): run auto_cases on false and psigma
  src/tactic/auto_cases.lean
Labels: ready-to-merge

#1409 chore(algebra/group/to_additive): map_namespace should make a meta constant
  src/algebra/group/to_additive.lean
Labels: ready-to-merge

#1393 feat(logic): make some decidability proofs [inline]
  src/logic/basic.lean
  test/logic_inline.lean
Labels: ready-to-merge

#1430 fix(algebra/*/colimits): avoid explicit `infer_instance`
  src/algebra/CommRing/colimits.lean
  src/algebra/Mon/colimits.lean
Labels: ready-to-merge

#1432 chore(*): renaming files constructing category instances
  src/algebra/CommRing/default.lean
  src/algebra/Mon/default.lean
  src/algebra/category/CommRing/adjunctions.lean
  src/algebra/category/CommRing/basic.lean
  src/algebra/category/CommRing/colimits.lean
  src/algebra/category/CommRing/default.lean
  src/algebra/category/CommRing/limits.lean
  src/algebra/category/Group.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/category/Mon/colimits.lean
  src/algebra/category/Mon/default.lean
  src/algebraic_geometry/presheafed_space.lean
  src/algebraic_geometry/stalks.lean
  src/category/fold.lean
  src/category_theory/category/Cat.lean
  src/category_theory/category/Groupoid.lean
  src/category_theory/category/Kleisli.lean
  src/category_theory/category/Rel.lean
  src/category_theory/category/default.lean
  src/category_theory/single_obj.lean
  src/measure_theory/category/Meas.lean
  src/measure_theory/giry_monad.lean
  src/topology/Top/default.lean
  src/topology/algebra/TopCommRing/default.lean
  src/topology/category/Top/adjunctions.lean
  src/topology/category/Top/basic.lean
  src/topology/category/Top/default.lean
  src/topology/category/Top/epi_mono.lean
  src/topology/category/Top/limits.lean
  src/topology/category/Top/open_nhds.lean
  src/topology/category/Top/opens.lean
  src/topology/category/TopCommRing.lean
  src/topology/category/UniformSpace.lean
  src/topology/sheaves/presheaf.lean
  src/topology/sheaves/presheaf_of_functions.lean
  src/topology/sheaves/stalks.lean
Labels: ready-to-merge

#1419 feat(well_founded_tactics): patch default_dec_tac
  docs/extras/well_founded_recursion.md
  docs/tactics.md
  src/computability/partrec_code.lean
  src/data/hash_map.lean
  src/data/list/basic.lean
  src/data/list/sort.lean
  src/data/nat/basic.lean
  src/data/vector2.lean
  src/set_theory/lists.lean
  src/tactic/basic.lean
  src/tactic/well_founded_tactics.lean
Labels: ready-to-merge

#1434 chore(category_theory/functor_category): improve comment warning about hcomp_assoc [ci skip]
  src/category_theory/functor_category.lean
Labels: ready-to-merge

#1435 feat(algebra/ring): add coercions from →+* to →* and →+
  src/algebra/ring.lean
Labels: ready-to-merge

#1436 chore(data/*): flipping inequalities
  src/algebra/archimedean.lean
  src/algebra/field_power.lean
  src/algebra/floor.lean
  src/algebra/gcd_domain.lean
  src/algebra/group_power.lean
  src/algebra/order.lean
  src/algebra/order_functions.lean
  src/algebra/ordered_group.lean
  src/algebra/ordered_ring.lean
  src/analysis/convex.lean
  src/analysis/specific_limits.lean
  src/computability/partrec_code.lean
  src/computability/primrec.lean
  src/data/equiv/fin.lean
  src/data/fin.lean
  src/data/finset.lean
  src/data/fintype.lean
  src/data/fp/basic.lean
  src/data/int/basic.lean
  src/data/int/modeq.lean
  src/data/list/basic.lean
  src/data/multiset.lean
  src/data/nat/basic.lean
  src/data/nat/cast.lean
  src/data/nat/dist.lean
  src/data/nat/gcd.lean
  src/data/nat/modeq.lean
  src/data/nat/pairing.lean
  src/data/nat/parity.lean
  src/data/nat/prime.lean
  src/data/nat/sqrt.lean
  src/data/nat/totient.lean
  src/data/num/lemmas.lean
  src/data/padics/padic_norm.lean
  src/data/padics/padic_numbers.lean
  src/data/pnat/basic.lean
  src/data/polynomial.lean
  src/data/rat/basic.lean
  src/data/rat/order.lean
  src/data/real/irrational.lean
  src/data/real/nnreal.lean
  src/data/zmod/basic.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/data/zsqrtd/basic.lean
  src/data/zsqrtd/gaussian_int.lean
  src/group_theory/perm/sign.lean
  src/group_theory/sylow.lean
  src/number_theory/sum_two_squares.lean
Labels: ready-to-merge

#1441 chore(algebra/group,logic/relator): review some explicit/implicit args
  src/algebra/group/hom.lean
  src/algebra/group/units.lean
  src/algebra/ring.lean
  src/data/list/basic.lean
  src/data/multiset.lean
  src/logic/relator.lean
Labels: ready-to-merge

#1413 chore(category_theory/notation): update notation for prod and coprod
  src/category_theory/limits/shapes/binary_products.lean
Labels: ready-to-merge

#1440 fix(docs/tutorial/category_theory): fix import
  .travis.yml
  docs/tutorial/category_theory/calculating_colimits_in_Top.lean
Labels: ready-to-merge

#1448 feat(data/nat/basic): dvd_add_self_{left,right}
  src/algebra/ring.lean
  src/data/nat/basic.lean
Labels: ready-to-merge

#1437 feat(data/list/sort): ordered_insert lemmas
  src/data/list/basic.lean
  src/data/list/sort.lean
Labels: ready-to-merge

#1447 feat(logic/basic): eq_iff_eq_cancel
  src/logic/basic.lean
Labels: ready-to-merge

#1442 feat(data/quot): define `quotient.map` and `quotient.map₂` (dep: 1441)
  src/data/quot.lean
  src/logic/relator.lean
Labels: ready-to-merge

#1412 fix(category_theory): require morphisms are in Type, again
  src/algebraic_geometry/presheafed_space.lean
  src/algebraic_geometry/stalks.lean
  src/category_theory/adjunction/limits.lean
  src/category_theory/category/Cat.lean
  src/category_theory/category/Groupoid.lean
  src/category_theory/category/default.lean
  src/category_theory/comma.lean
  src/category_theory/conj.lean
  src/category_theory/core.lean
  src/category_theory/currying.lean
  src/category_theory/discrete_category.lean
  src/category_theory/endomorphism.lean
  src/category_theory/functor_category.lean
  src/category_theory/groupoid.lean
  src/category_theory/hom_functor.lean
  src/category_theory/limits/cones.lean
  src/category_theory/limits/functor_category.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/opposites.lean
  src/category_theory/limits/over.lean
  src/category_theory/limits/preserves.lean
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/limits/shapes/constructions/limits_of_products_and_equalizers.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/finite_limits.lean
  src/category_theory/limits/shapes/finite_products.lean
  src/category_theory/limits/shapes/products.lean
  src/category_theory/limits/shapes/pullbacks.lean
  src/category_theory/limits/shapes/terminal.lean
  src/category_theory/monad/limits.lean
  src/category_theory/monoidal/category.lean
  src/category_theory/monoidal/functor.lean
  src/category_theory/monoidal/of_has_finite_products.lean
  src/category_theory/monoidal/types.lean
  src/category_theory/natural_transformation.lean
  src/category_theory/pempty.lean
  src/category_theory/products/associator.lean
  src/category_theory/products/basic.lean
  src/category_theory/products/bifunctor.lean
  src/category_theory/sums/associator.lean
  src/category_theory/sums/basic.lean
  src/category_theory/types.lean
  src/category_theory/yoneda.lean
  src/topology/category/Top/open_nhds.lean
  src/topology/category/Top/opens.lean
  src/topology/sheaves/presheaf.lean
  src/topology/sheaves/stalks.lean
Labels: ready-to-merge

#1274 feat(set_theory/game): the theory of combinatorial games
  docs/references.bib
  src/algebra/ordered_group.lean
  src/data/equiv/basic.lean
  src/data/finset.lean
  src/data/multiset.lean
  src/linear_algebra/dimension.lean
  src/logic/basic.lean
  src/set_theory/game.lean
  src/set_theory/pgame.lean
  src/set_theory/surreal.lean
Labels: ready-to-merge

#1457 chore(data/set/lattice): missing colon in front of author list [ci skip]
  src/data/set/lattice.lean
Labels: ready-to-merge

#1456 refactor(algebra/big_operators,data/finset): use `finset.disjoint` in definitions
  src/algebra/big_operators.lean
  src/data/finset.lean
  src/data/nat/totient.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/group_theory/order_of_element.lean
  src/topology/algebra/infinite_sum.lean
Labels: ready-to-merge

#1459 chore(topology/maps): a few tweaks to open_embedding and closed embeddings
  src/topology/maps.lean
Labels: ready-to-merge

#1380 refactor(category_theory): refactor concrete categories
  docs/references.bib
  src/algebra/category/CommRing/adjunctions.lean
  src/algebra/category/CommRing/basic.lean
  src/algebra/category/CommRing/colimits.lean
  src/algebra/category/CommRing/limits.lean
  src/algebra/category/Group.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/category/Mon/colimits.lean
  src/algebra/punit_instances.lean
  src/algebra/ring.lean
  src/algebraic_geometry/stalks.lean
  src/category_theory/category/Cat.lean
  src/category_theory/category/Groupoid.lean
  src/category_theory/concrete_category.lean
  src/category_theory/concrete_category/basic.lean
  src/category_theory/concrete_category/bundled.lean
  src/category_theory/concrete_category/bundled_hom.lean
  src/category_theory/concrete_category/default.lean
  src/category_theory/concrete_category/unbundled_hom.lean
  src/category_theory/fully_faithful.lean
  src/category_theory/functor.lean
  src/category_theory/limits/cones.lean
  src/category_theory/single_obj.lean
  src/data/mv_polynomial.lean
  src/logic/function.lean
  src/measure_theory/category/Meas.lean
  src/topology/category/Top/adjunctions.lean
  src/topology/category/Top/basic.lean
  src/topology/category/Top/epi_mono.lean
  src/topology/category/Top/limits.lean
  src/topology/category/TopCommRing.lean
  src/topology/category/UniformSpace.lean
  src/topology/sheaves/presheaf_of_functions.lean
  src/topology/uniform_space/basic.lean
Labels: ready-to-merge

#1461 chore(category_theory/endomorphism): make `map_End` and `map_Aut` use bundled homs
  src/category_theory/endomorphism.lean
  src/category_theory/isomorphism.lean
Labels: ready-to-merge

#1443 chore(algebra/group): rename `as_monoid_hom` into `monoid_hom.of`, define `ring_hom.of`
  src/algebra/associated.lean
  src/algebra/group/hom.lean
  src/algebra/group/units_hom.lean
  src/algebra/ring.lean
Labels: ready-to-merge

#1463 chore(data/pfun): run `#sanity_check`
  src/data/pfun.lean
Labels: ready-to-merge

#1431 chore(algebra/group/units): use `def to_units` instead of `has_lift`
  src/algebra/group/units.lean
  src/data/equiv/algebra.lean
Labels: ready-to-merge

#1467 feat(tactic/interactive): add fconstructor
  src/tactic/interactive.lean
Labels: ready-to-merge

#1427 fix(category_theory/finite_limits): fix definition, and construct from finite products and equalizers
  src/category_theory/discrete_category.lean
  src/category_theory/limits/shapes/constructions/finite_limits.lean
  src/category_theory/limits/shapes/constructions/limits_of_products_and_equalizers.lean
  src/category_theory/limits/shapes/finite_limits.lean
  src/category_theory/limits/shapes/finite_products.lean
Labels: ready-to-merge

#1469 chore(*): fix various issues reported by `sanity_check_mathlib`
  src/algebra/direct_limit.lean
  src/algebra/field.lean
  src/algebra/group/basic.lean
  src/algebra/group/with_one.lean
  src/algebra/ordered_field.lean
  src/algebra/ordered_ring.lean
  src/algebra/pointwise.lean
  src/category/monad/cont.lean
  src/category/traversable/equiv.lean
  src/category_theory/natural_isomorphism.lean
  src/data/equiv/algebra.lean
  src/data/equiv/basic.lean
  src/data/finset.lean
  src/data/finsupp.lean
  src/data/matrix/basic.lean
  src/data/multiset.lean
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/data/rat/basic.lean
  src/data/rat/order.lean
  src/group_theory/free_group.lean
  src/group_theory/sylow.lean
  src/linear_algebra/finsupp_vector_space.lean
  src/logic/basic.lean
  src/measure_theory/ae_eq_fun.lean
  src/number_theory/dioph.lean
  src/order/filter/basic.lean
  src/order/filter/pointwise.lean
  src/ring_theory/algebra.lean
  src/ring_theory/ideals.lean
  src/ring_theory/power_series.lean
  src/set_theory/ordinal.lean
  src/set_theory/pgame.lean
  src/set_theory/surreal.lean
  src/set_theory/zfc.lean
  src/tactic/doc_blame.lean
  src/tactic/monotonicity/interactive.lean
  src/tactic/omega/clause.lean
  src/tactic/omega/coeffs.lean
  src/tactic/omega/nat/form.lean
  src/tactic/omega/nat/preterm.lean
  src/tactic/ring.lean
Labels: ready-to-merge

#1475 feat(tactic/core): derive handler for simple instances
  src/tactic/core.lean
  test/delta_instance.lean
Labels: ready-to-merge

#1454 feat(topology/constructions): is_open_prod_iff'
  src/data/set/basic.lean
  src/topology/constructions.lean
Labels: ready-to-merge

#1466 feat(data|set_theory): various new lemmas
  src/algebra/ordered_ring.lean
  src/data/equiv/basic.lean
  src/data/equiv/list.lean
  src/data/fin.lean
  src/data/list/basic.lean
  src/data/nat/basic.lean
  src/data/set/basic.lean
  src/data/subtype.lean
  src/set_theory/cardinal.lean
  src/set_theory/ordinal.lean
Labels: ready-to-merge

#1476 refactor(algebra/*): Make `monoid_hom.ext` etc use `∀ x, f x = g x` as an assumption
  src/algebra/category/CommRing/adjunctions.lean
  src/algebra/category/CommRing/basic.lean
  src/algebra/category/CommRing/limits.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/group/hom.lean
  src/algebra/ring.lean
  src/data/mv_polynomial.lean
Labels: ready-to-merge

#1478 fix(tactic.lift): fix error messages
  src/tactic/lift.lean
  test/tactics.lean
Labels: ready-to-merge

#1470 feat(tactic/library_search): a more powerful library_search
  src/tactic/library_search.lean
  src/tactic/solve_by_elim.lean
  test/library_search/basic.lean
  test/solve_by_elim.lean
Labels: ready-to-merge

#1433 feat(algebra/continued_fractions): add basic defs/lemmas for continued fractions
  docs/references.bib
  src/algebra/continued_fractions/basic.lean
  src/algebra/continued_fractions/continuants_recurrence.lean
  src/algebra/continued_fractions/default.lean
  src/algebra/continued_fractions/translations.lean
  src/data/seq/seq.lean
Labels: ready-to-merge

#1471 feat(algebra/big_operators): simp lemmas
  src/algebra/big_operators.lean
  src/data/finset.lean
Labels: ready-to-merge

#1477 feat(finset): add has_sep instance
  src/data/finset.lean
  test/examples.lean
Labels: ready-to-merge

#1485 cleanup(*): use priority 10 for low priority
  src/analysis/calculus/deriv.lean
  src/analysis/calculus/times_cont_diff.lean
  src/category/bifunctor.lean
  src/category/bitraversable/instances.lean
  src/category_theory/adjunction/basic.lean
  src/computability/primrec.lean
  src/data/fintype.lean
  src/data/int/basic.lean
  src/data/nat/cast.lean
  src/data/num/basic.lean
  src/data/rat/cast.lean
  src/field_theory/splitting_field.lean
  src/group_theory/sylow.lean
  src/linear_algebra/finsupp.lean
  src/logic/basic.lean
  src/logic/function.lean
  src/tactic/finish.lean
  src/tactic/localized.lean
  src/tactic/push_neg.lean
  src/topology/algebra/uniform_group.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/gromov_hausdorff_realized.lean
  src/topology/uniform_space/abstract_completion.lean
Labels: ready-to-merge

#1480 chore(scripts): add executable bit to scripts/mk_all.sh, and create/delete sanity_check_mathlib.lean
  .gitignore
  scripts/mk_all.sh
  scripts/rm_all.sh
Labels: ready-to-merge

#1487 feat(sanity_check): improvements
  docs/tactics.md
  src/meta/expr.lean
  src/tactic/sanity_check.lean
  test/sanity_check.lean
Labels: ready-to-merge

#1486 feat(int/basic): add simp-lemma int.of_nat_eq_coe
  src/data/bool.lean
  src/data/int/basic.lean
  src/data/rat/basic.lean
Labels: ready-to-merge

#1482 refactor(data/equiv/algebra): rewrite `ring_equiv` using bundled homs
  src/algebra/ring.lean
  src/data/equiv/algebra.lean
  src/data/mv_polynomial.lean
  src/ring_theory/free_comm_ring.lean
  src/ring_theory/ideal_operations.lean
  src/ring_theory/localization.lean
  src/ring_theory/maps.lean
  src/ring_theory/noetherian.lean
Labels: ready-to-merge

#1453 feat(data/setoid): create file about setoids
  src/data/list/basic.lean
  src/data/set/lattice.lean
  src/data/setoid.lean
  src/order/galois_connection.lean
Labels: ready-to-merge

#1449 feat(field_theory/minimal_polynomial): Basics on minimal polynomials
  src/data/nat/basic.lean
  src/data/polynomial.lean
  src/field_theory/minimal_polynomial.lean
  src/ring_theory/algebra.lean
  src/ring_theory/polynomial.lean
  src/ring_theory/power_series.lean
Labels: ready-to-merge

#1488 fix(scripts/mk_all): ignore hidden files
  scripts/mk_all.sh
Labels: ready-to-merge

#1490 chore(*): drop some unused args reported by `#sanity_check_mathlib`
  src/algebra/archimedean.lean
  src/algebra/associated.lean
  src/algebra/floor.lean
  src/algebra/group/units.lean
  src/algebra/group/with_one.lean
  src/category/basic.lean
  src/category/bitraversable/instances.lean
  src/category/monad/writer.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/pullbacks.lean
  src/data/equiv/algebra.lean
  src/data/equiv/basic.lean
  src/measure_theory/ae_eq_fun.lean
  src/measure_theory/borel_space.lean
  src/measure_theory/l1_space.lean
  src/measure_theory/measurable_space.lean
  src/number_theory/pell.lean
  src/topology/instances/polynomial.lean
Labels: ready-to-merge

#1479 feat(data/int/basic): to_nat lemmas
  src/data/int/basic.lean
Labels: ready-to-merge

#1474 feat(logic/function): define `function.involutive`
  src/algebra/field.lean
  src/algebra/group/basic.lean
  src/algebra/group_power.lean
  src/analysis/complex/polynomial.lean
  src/data/complex/basic.lean
  src/data/equiv/basic.lean
  src/data/real/hyperreal.lean
  src/data/real/nnreal.lean
  src/logic/function.lean
Labels: ready-to-merge

#1402 feat(reduce_projections): add reduce_projections attribute
  docs/tactics.md
  src/meta/expr.lean
  src/tactic/basic.lean
  src/tactic/core.lean
  src/tactic/default.lean
  src/tactic/simps.lean
  test/simps.lean
  test/tactics.lean
Labels: ready-to-merge

#1492 chore(algebra/char_p): remove some decidable_eq assumptions
  src/algebra/char_p.lean
  src/data/set/finite.lean
Labels: ready-to-merge

#1495 chore(algebra/group_power): move inv_one from group_power to field
  src/algebra/field.lean
  src/algebra/group_power.lean
Labels: ready-to-merge

#1422 feat(geometry/manifold/manifold): define manifolds
  src/geometry/manifold/manifold.lean
Labels: ready-to-merge

#1497 chore(order/basic): rename `monotone_comp` to `monotone.comp`, reorder arguments
  src/order/basic.lean
  src/order/filter/lift.lean
  src/order/fixed_points.lean
  src/topology/uniform_space/basic.lean
  src/topology/uniform_space/cauchy.lean
  src/topology/uniform_space/completion.lean
Labels: ready-to-merge

#1292 feat(ring_theory/power_series): order
  src/ring_theory/ideal_operations.lean
  src/ring_theory/power_series.lean
Labels: ready-to-merge, request-review

#1404 chore(linear_algebra): continue removing decidable_eq assumptions
  src/field_theory/finite_card.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/dimension.lean
  src/linear_algebra/dual.lean
  src/linear_algebra/finite_dimensional.lean
  src/linear_algebra/finsupp_vector_space.lean
  src/linear_algebra/matrix.lean
  src/ring_theory/noetherian.lean
Labels: ready-to-merge, request-review
