Repository leanprover-community/mathlib, pull requests merged in 2020-03, with the labels that each got.

#2060 feat(algebra/free_monoid): define `lift` and `map`, move out of `algebra/group`
  src/algebra/free_monoid.lean
  src/algebra/group/default.lean
  src/algebra/group/free_monoid.lean
  src/category/fold.lean
  src/ring_theory/free_ring.lean
Labels: ready-to-merge

#2052 feat(order/galois_connection): lemmas about galois insertions and supr/infi
  src/order/galois_connection.lean
  src/topology/opens.lean
Labels: ready-to-merge

#2073 chore(topology/metric_space/isometry): rename `(e)metric.isometry.diam_image` to `isometry.(e)diam_image`
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/gromov_hausdorff_realized.lean
  src/topology/metric_space/isometry.lean
Labels: ready-to-merge

#2056 chore(algebra/group): move `is_mul/monoid/group_hom` to `deprecated/`
  src/algebra/group/conj.lean
  src/algebra/group/hom.lean
  src/algebra/group/is_unit.lean
  src/algebra/group/type_tags.lean
  src/algebra/group/units_hom.lean
  src/algebra/group/with_one.lean
  src/algebra/ring.lean
  src/deprecated/group.lean
  src/group_theory/perm/sign.lean
Labels: ready-to-merge

#2074 chore(data/real/ennreal): weaker assumptions in `sub_mul`, add `coe_inv_le`
  src/data/real/ennreal.lean
Labels: ready-to-merge

#2068 feat(data/finset): new basic material on finsets and fintypes
  src/data/finset.lean
  src/data/fintype.lean
  src/data/fintype/card.lean
  src/measure_theory/integration.lean
Labels: ready-to-merge

#2055 doc(data/fin): add docs; fin_zero_elim -> fin.elim0; fin_zero_elim' -> fin_zero_elim
  src/data/fin.lean
Labels: ready-to-merge

#1596 feat(tactic/nat_cases): a tactic to case bash inequalities on natural numbers
  docs/tactics.md
  src/algebra/ordered_group.lean
  src/data/finset.lean
  src/data/fintype/intervals.lean
  src/data/list/basic.lean
  src/data/nat/basic.lean
  src/data/pnat/basic.lean
  src/data/pnat/intervals.lean
  src/tactic/default.lean
  src/tactic/fin_cases.lean
  src/tactic/interval_cases.lean
  test/fin_cases.lean
  test/interval_cases.lean
Labels: ready-to-merge

#2067 feat(analysis/calculus/iterated_deriv): iterated derivative of a function defined on the base field
  src/analysis/calculus/iterated_deriv.lean
  src/analysis/calculus/times_cont_diff.lean
Labels: ready-to-merge

#2071 feat(data/list/basic): more lemmas about `list.chain'`; `chain'_of_pairwise` → `pairwise.chain'`
  src/data/list/basic.lean
Labels: ready-to-merge

#2078 docs(*): fix some docstrings
  src/category/monad/writer.lean
  src/category_theory/concrete_category/bundled_hom.lean
Labels: ready-to-merge

#2075 feat(topology/metric_space/antilipschitz): define `antilipschitz_with`
  src/analysis/ODE/gronwall.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/finite_dimension.lean
  src/analysis/normed_space/operator_norm.lean
  src/measure_theory/bochner_integration.lean
  src/topology/bounded_continuous_function.lean
  src/topology/metric_space/antilipschitz.lean
  src/topology/metric_space/contracting.lean
  src/topology/metric_space/gromov_hausdorff_realized.lean
  src/topology/metric_space/isometry.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#2076 feat(tactic/extract_goal): improve formatting to put assumptions on their own line
  src/tactic/interactive.lean
Labels: ready-to-merge

#2082 fix(ci): adjust conditions for fixing steps
  .github/workflows/build.yml
  scripts/deploy_docs.sh
Labels: ready-to-merge

#2085 chore(analysis/normed_space/basic): rename `ne_mem_of_tendsto_norm_at_top`
  src/analysis/calculus/fderiv.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/normed_space/basic.lean
Labels: ready-to-merge

#2086 fix(congruence): use has_coe_t instead of has_coe
  src/group_theory/congruence.lean
Labels: ready-to-merge

#2084 refactor(algebra/lie_algebra): lie_algebra should not extend lie_ring
  src/algebra/lie_algebra.lean
  src/algebra/ordered_group.lean
Labels: ready-to-merge

#2087 feat(analysis/calculus/specific_functions): smoothness of exp(-1/x)
  src/algebra/field.lean
  src/analysis/calculus/specific_functions.lean
  test/ring.lean
Labels: ready-to-merge

#2072 feat(data/traversable): improve support for instances for recursive types
  src/category/traversable/derive.lean
  test/examples.lean
Labels: changes-requested

#2088 feat(category_theory/limits): the kernel of the cokernel of an epimorphism is an isomorphism
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
Labels: ready-to-merge

#2083 fix(category_theory/limits): Add some missing instances for special shapes of limits
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
  src/category_theory/limits/shapes/pullbacks.lean
Labels: ready-to-merge

#2004 refactor(group_theory/monoid_localization): use characteristic predicate
  src/algebra/group/basic.lean
  src/algebra/group/hom.lean
  src/algebra/group/is_unit.lean
  src/algebra/group/units.lean
  src/algebra/group/units_hom.lean
  src/algebra/pi_instances.lean
  src/group_theory/monoid_localization.lean
  src/group_theory/submonoid.lean
Labels: ready-to-merge

#2091 feat(data/set/lattice): add @[simp] to lemmas
  src/data/set/finite.lean
  src/data/set/lattice.lean
  src/measure_theory/integration.lean
  src/topology/instances/real.lean
  src/topology/uniform_space/cauchy.lean
Labels: ready-to-merge

#2089 feat(lint): add two new linters
  docs/commands.md
  src/tactic/core.lean
  src/tactic/lint.lean
  test/lint.lean
Labels: ready-to-merge

#1368 feat(data/fin_enum): `fin_enum` class for finite types with an enumeration order
  docs/tactics.md
  src/data/fin.lean
  src/data/fin_enum.lean
  src/data/finset.lean
  src/data/list/basic.lean
  src/tactic/monotonicity/interactive.lean
Labels: ready-to-merge

#2105 chore(category_theory/limits): remove limits.lean which is superseded by limits_of_products_and_equalizers.lean
  src/category_theory/limits/shapes/constructions/limits.lean
Labels: ready-to-merge

#2103 chore(category_theory/functor): make arguments implicit
  src/category_theory/functor.lean
Labels: ready-to-merge

#2096 fix(deprecated/group): remove dangerous instances
  src/deprecated/group.lean
  src/group_theory/quotient_group.lean
  src/group_theory/subgroup.lean
Labels: ready-to-merge

#2099 chore(algebra/group): streamlining imports
  src/algebra/associated.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/char_zero.lean
  src/algebra/group_power.lean
  src/algebra/ordered_group.lean
  src/algebra/pi_instances.lean
  src/algebra/punit_instances.lean
  src/algebra/ring.lean
  src/group_theory/free_group.lean
Labels: ready-to-merge

#2104 doc(docs/tutorial/category_theory): introductory category theory tutorial
  docs/tutorial/category_theory/intro.lean
Labels: ready-to-merge

#2107 refactor(analysis/normed_space/banach): use bundled `→L[𝕜]` maps
  src/analysis/normed_space/banach.lean
Labels: ready-to-merge

#2111 refactor(topology/algebra/ordered): rename `tendsto_of_tendsto_of_tendsto_of_le_of_le` to `tendsto_of_tendsto_of_tendsto_of_le_of_le'`
  src/analysis/normed_space/real_inner_product.lean
  src/topology/algebra/ordered.lean
  src/topology/metric_space/basic.lean
Labels: ready-to-merge

#2100 feat(category_theory): images
  src/category_theory/category/default.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/images.lean
Labels: ready-to-merge

#2110 feat(analysis/calculus/darboux): IVT for derivatives
  src/analysis/calculus/darboux.lean
  src/analysis/calculus/local_extr.lean
Labels: ready-to-merge

#2112 feat(algebra/group/hom): cancel injective/surjective `monoid_hom`s
  src/algebra/group/hom.lean
  src/algebra/ring.lean
Labels: ready-to-merge

#2115 reflexive transitive closure is symmetric of original
  src/logic/relation.lean
Labels: ready-to-merge

#2117 chore(ring_theory/polynomial): refactor proof of is_noetherian_ring_fin
  src/ring_theory/polynomial.lean
Labels: ready-to-merge

#2116 feat(linter): include linter name in report
  src/tactic/lint.lean
Labels: ready-to-merge

#2113 feat(category_theory/limits): the pullback of a monomorphism is a monomorphism
  src/category_theory/limits/shapes/constructions/binary_products.lean
  src/category_theory/limits/shapes/pullbacks.lean
Labels: ready-to-merge

#2108 feat(analysis/calculus/tangent_cone): prove that all intervals are `unique_diff_on`
  src/analysis/calculus/tangent_cone.lean
Labels: ready-to-merge

#2119 feat(ring_theory/polynomial): refactor of is_integral_domain_fin
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/ring_theory/polynomial.lean
Labels: ready-to-merge

#2092 feat(measurable_space): is_measurable_supr lemma
  src/measure_theory/measurable_space.lean
Labels: ready-to-merge

#2094 feat(ci): look for equivalent oleans on Azure
  .github/workflows/build.yml
  scripts/fetch_olean_cache.sh
  scripts/look_up_olean_hash.py
  scripts/write_azure_table_entry.py
Labels: ready-to-merge

#2122 fix(category_theory/limits): add two missing duals
  src/category_theory/limits/shapes/equalizers.lean
Labels: ready-to-merge

#2126 fix(algebra/category): avoid deprecated lemmas
  src/algebra/category/CommRing/colimits.lean
  src/algebra/category/Mon/colimits.lean
Labels: ready-to-merge

#2127 chore(category_theory): remove functor.of
  src/category_theory/comma.lean
  src/category_theory/elements.lean
  src/category_theory/punit.lean
Labels: ready-to-merge

#2128 chore(category_theory/cones): make functor argument of forget explicit
  src/category_theory/limits/cones.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
Labels: ready-to-merge

#2124 feat(category_theory/limits): construct equalizers from pullbacks and products
  src/category_theory/category/default.lean
  src/category_theory/limits/shapes/constructions/equalizers.lean
Labels: ready-to-merge

#2069 feat(topology): is_closed_proj_of_compact
  src/data/set/basic.lean
  src/data/set/lattice.lean
  src/order/filter/basic.lean
  src/order/lattice.lean
  src/ring_theory/free_comm_ring.lean
  src/topology/algebra/ordered.lean
  src/topology/subset_properties.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#2137 fix(category_theory/limits): rename binary_cofan.mk_π_app_left to binary_cofan.mk_ι_app_left
  src/category_theory/limits/shapes/binary_products.lean
Labels: ready-to-merge

#2132 feat(category_theory/opposites): add nat_iso.unop
  src/category_theory/opposites.lean
Labels: ready-to-merge

#2093 doc(*): switch from update-mathlib to leanproject
  docs/contribute/index.md
  docs/install/debian.md
  docs/install/debian_details.md
  docs/install/linux.md
  docs/install/project.md
  docs/install/windows.md
Labels: ready-to-merge

#2136 chore(algebra/field*, field_theory/subfield): drop some `x ≠ 0`, use `division_ring`
  src/algebra/field.lean
  src/algebra/field_power.lean
  src/field_theory/subfield.lean
Labels: ready-to-merge

#2133 refactor(*): migrate some files to bundled ring homs
  src/algebra/big_operators.lean
  src/algebra/direct_limit.lean
  src/algebra/pi_instances.lean
  src/algebra/ring.lean
  src/ring_theory/adjoin.lean
  src/ring_theory/adjoin_root.lean
  src/ring_theory/free_comm_ring.lean
  src/ring_theory/ideal_operations.lean
  src/ring_theory/ideals.lean
  src/ring_theory/integral_closure.lean
  src/ring_theory/localization.lean
  src/ring_theory/noetherian.lean
  src/ring_theory/power_series.lean
  src/ring_theory/subring.lean
Labels: ready-to-merge

#2123 chore(linear_algebra/basic): simplify two proofs
  src/linear_algebra/basic.lean
  src/ring_theory/ideal_operations.lean
  src/ring_theory/ideals.lean
  src/ring_theory/noetherian.lean
  src/ring_theory/polynomial.lean
Labels: ready-to-merge

#2142 chore(algebra/category/CommRing/limits): avoid `is_ring_hom`
  src/algebra/category/CommRing/limits.lean
Labels: ready-to-merge

#2139 feat(category_theory/limits): derive has_binary_products from has_limit (pair X Y)
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/pullbacks.lean
Labels: ready-to-merge

#2144 refactor(ring_theory/subring): use bundled homs
  src/field_theory/subfield.lean
  src/ring_theory/integral_closure.lean
  src/ring_theory/subring.lean
Labels: ready-to-merge

#2125 feat(algebra): monoidal category of R-modules
  src/algebra/category/Module/basic.lean
  src/algebra/category/Module/monoidal.lean
  src/category_theory/limits/types.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/tensor_product.lean
Labels: ready-to-merge

#2141 feat(algebra/category/Group): the free-forgetful adjunction for AddCommGroup
  src/algebra/category/Group/adjunctions.lean
  src/algebra/group/hom.lean
  src/group_theory/free_abelian_group.lean
Labels: ready-to-merge

#2130 feat(algebra): the forgetful functor Module ℤ ⥤ Ab is an equivalence
  src/algebra/category/Group.lean
  src/algebra/category/Group/Z_Module_equivalence.lean
  src/algebra/category/Module/basic.lean
  src/algebra/module.lean
Labels: ready-to-merge

#2147 refactor(data/equiv/algebra): split
  src/algebra/category/CommRing/basic.lean
  src/algebra/category/Mon/basic.lean
  src/algebra/free_monoid.lean
  src/algebra/semiconj.lean
  src/category_theory/endomorphism.lean
  src/category_theory/single_obj.lean
  src/data/equiv/algebra.lean
  src/data/equiv/mul_add.lean
  src/data/equiv/ring.lean
  src/data/equiv/transfer_instance.lean
  src/data/mv_polynomial.lean
  src/field_theory/finite.lean
  src/group_theory/submonoid.lean
  src/linear_algebra/basic.lean
  src/ring_theory/free_comm_ring.lean
  src/ring_theory/free_ring.lean
  src/ring_theory/ideal_operations.lean
  src/ring_theory/localization.lean
  src/ring_theory/maps.lean
  src/ring_theory/noetherian.lean
  src/topology/algebra/group.lean
Labels: ready-to-merge

#2131 feat(category_theory/comma): some limits in the over category and iterated slices
  src/category_theory/comma.lean
  src/category_theory/limits/over.lean
  src/category_theory/limits/shapes/constructions/equalizers.lean
  src/category_theory/limits/shapes/pullbacks.lean
Labels: ready-to-merge

#2151 doc(docs/install/*): emphasize projects link
  docs/install/debian_details.md
  docs/install/linux.md
  docs/install/macos.md
Labels: ready-to-merge

#2134 feat(category_theory): comonads and coalgebras
  scripts/nolints.txt
  src/category_theory/monad/algebra.lean
  src/category_theory/monad/basic.lean
Labels: ready-to-merge

#2148 refactor(logic/function): inv_fun takes a nonempty instance instead of inhabited
  src/logic/function.lean
Labels: ready-to-merge

#2157 chore(field_theory/finite): spelling mistake
  src/field_theory/finite.lean
Labels: ready-to-merge

#2159 chore(nnreal): replace coe_le with coe_le_coe
  src/analysis/convex/topology.lean
  src/analysis/mean_inequalities.lean
  src/analysis/normed_space/basic.lean
  src/analysis/specific_limits.lean
  src/data/real/ennreal.lean
  src/data/real/nnreal.lean
  src/measure_theory/decomposition.lean
  src/measure_theory/simple_func_dense.lean
  src/topology/instances/ennreal.lean
  src/topology/metric_space/basic.lean
Labels: ready-to-merge

#2156 feat(category_theory/limits): kernel forks
  src/category_theory/limits/shapes/kernels.lean
Labels: ready-to-merge

#2143 feat(category_theory/limits): pullbacks from binary products and equalizers
  src/category_theory/limits/over.lean
  src/category_theory/limits/shapes/constructions/equalizers.lean
  src/category_theory/limits/shapes/constructions/pullbacks.lean
  src/category_theory/limits/shapes/pullbacks.lean
Labels: ready-to-merge

#2155 feat(category_theory/limits): Convenience methods for building limit (co)forks
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
Labels: ready-to-merge

#2160 feat(analysis/normed_space/operator_norm): completeness of the space of operators
  src/analysis/normed_space/operator_norm.lean
Labels: ready-to-merge

#2138 feat(category_theory/monad/limits): forgetful creates colimits
  src/category_theory/monad/limits.lean
Labels: ready-to-merge

#2153 feat(category_theory/image): comparison maps for precomposition
  src/category_theory/limits/shapes/images.lean
Labels: ready-to-merge

#2150 doc(docs/install/windows): emphasize projects link
  docs/install/windows.md
Labels: ready-to-merge

#2114 feat(tactic): command for adding tactic, command, and attribute documentation
  docs/contribute/doc.md
  docs/extras.md
  docs/extras/simp.md
  src/logic/basic.lean
  src/tactic/abel.lean
  src/tactic/alias.lean
  src/tactic/apply_fun.lean
  src/tactic/cache.lean
  src/tactic/clear.lean
  src/tactic/core.lean
  src/tactic/derive_inhabited.lean
  src/tactic/doc_commands.lean
  src/tactic/elide.lean
  src/tactic/explode.lean
  src/tactic/ext.lean
  src/tactic/fin_cases.lean
  src/tactic/find.lean
  src/tactic/finish.lean
  src/tactic/hint.lean
  src/tactic/interactive.lean
  src/tactic/interval_cases.lean
  src/tactic/library_note.lean
  src/tactic/lift.lean
  src/tactic/linarith.lean
  src/tactic/lint.lean
  src/tactic/localized.lean
  src/tactic/monotonicity/interactive.lean
  src/tactic/norm_cast.lean
  src/tactic/norm_num.lean
  src/tactic/omega/main.lean
  src/tactic/pi_instances.lean
  src/tactic/push_neg.lean
  src/tactic/rcases.lean
  src/tactic/reassoc_axiom.lean
  src/tactic/rename.lean
  src/tactic/rename_var.lean
  src/tactic/replacer.lean
  src/tactic/restate_axiom.lean
  src/tactic/rewrite.lean
  src/tactic/ring.lean
  src/tactic/ring_exp.lean
  src/tactic/simp_rw.lean
  src/tactic/simpa.lean
  src/tactic/simps.lean
  src/tactic/solve_by_elim.lean
  src/tactic/squeeze.lean
  src/tactic/suggest.lean
  src/tactic/tauto.lean
  src/tactic/tfae.lean
  src/tactic/tidy.lean
  src/tactic/where.lean
Labels: ready-to-merge

#2162 chore(order/liminf_limsup): lint and cleanup the file
  src/order/filter/basic.lean
  src/order/liminf_limsup.lean
Labels: ready-to-merge

#2146 feat(category_theory): split epis and monos, and a result about (co)projections
  src/category_theory/epi_mono.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
  src/category_theory/limits/shapes/zero.lean
Labels: ready-to-merge

#2167 feat(data/real/*nnreal): add division lemmas
  src/data/real/ennreal.lean
  src/data/real/nnreal.lean
  src/topology/instances/ennreal.lean
Labels: ready-to-merge

#2090 feat(lint): run some linters on automatically generated declarations
  scripts/mk_nolint.lean
  src/analysis/normed_space/basic.lean
  src/category_theory/limits/shapes/finite_limits.lean
  src/category_theory/limits/shapes/images.lean
  src/data/fin_enum.lean
  src/ring_theory/principal_ideal_domain.lean
  src/tactic/lint.lean
  src/topology/subset_properties.lean
  test/lint.lean
Labels: ready-to-merge

#2169 fix(category_theory/limits): require explicit instances of has_zero_morphisms
  src/algebra/category/Module/basic.lean
  src/category_theory/limits/shapes/kernels.lean
  src/category_theory/limits/shapes/zero.lean
Labels: ready-to-merge

#2101 feat(category_theory): images in Ab and Type
  src/algebra/category/Group/adjunctions.lean
  src/algebra/category/Group/basic.lean
  src/algebra/category/Group/images.lean
  src/algebra/group_power.lean
  src/category_theory/concrete_category/basic.lean
  src/category_theory/limits/shapes/images.lean
  src/category_theory/limits/types.lean
  src/group_theory/subgroup.lean
Labels: ready-to-merge

#2164 feat(analysis/complex/exponential): real powers of nnreals
  src/analysis/complex/exponential.lean
  src/analysis/mean_inequalities.lean
Labels: ready-to-merge

#2165 feat(topology/bounded_continuous_functions): more general uniform convergence
  src/topology/bounded_continuous_function.lean
  src/topology/continuous_on.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/emetric_space.lean
Labels: ready-to-merge

#2106 chore(*): switch to lean 3.7.1c
  leanpkg.toml
  scripts/deploy_docs.sh
  src/algebra/direct_limit.lean
  src/algebra/direct_sum.lean
  src/algebra/euclidean_domain.lean
  src/algebra/ordered_group.lean
  src/algebra/ordered_ring.lean
  src/algebra/ring.lean
  src/analysis/normed_space/banach.lean
  src/analysis/normed_space/real_inner_product.lean
  src/category/monad/writer.lean
  src/category_theory/limits/preserves.lean
  src/category_theory/monad/limits.lean
  src/data/fintype.lean
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/deprecated/group.lean
  src/field_theory/splitting_field.lean
  src/group_theory/free_abelian_group.lean
  src/group_theory/free_group.lean
  src/group_theory/presented_group.lean
  src/group_theory/quotient_group.lean
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
  src/ring_theory/algebra.lean
  src/ring_theory/localization.lean
  src/set_theory/ordinal.lean
  src/tactic/alias.lean
  src/tactic/core.lean
  src/tactic/lint.lean
  src/tactic/reassoc_axiom.lean
  src/tactic/squeeze.lean
  src/tactic/transport.lean
  src/topology/algebra/group_completion.lean
  src/topology/algebra/infinite_sum.lean
  src/topology/algebra/ring.lean
  src/topology/algebra/uniform_group.lean
  src/topology/algebra/uniform_ring.lean
Labels: ready-to-merge

#2171 feat(topology/algebra/infinite_sum): dot notation, cauchy sequences
  src/analysis/normed_space/banach.lean
  src/analysis/normed_space/basic.lean
  src/analysis/specific_limits.lean
  src/data/option/basic.lean
  src/data/real/cardinality.lean
  src/measure_theory/outer_measure.lean
  src/measure_theory/probability_mass_function.lean
  src/order/liminf_limsup.lean
  src/topology/algebra/infinite_sum.lean
  src/topology/instances/ennreal.lean
  src/topology/instances/nnreal.lean
  src/topology/uniform_space/cauchy.lean
Labels: ready-to-merge

#2184 chore(category_theory/binary_products): tweak spacing in notation
  src/category_theory/limits/shapes/binary_products.lean
Labels: ready-to-merge

#2181 chore(category_theory/isomorphism): use @[simps]
  src/category_theory/isomorphism.lean
Labels: ready-to-merge, request-review

#2154 feat(category_theory): regular monos
  src/category_theory/epi_mono.lean
  src/category_theory/limits/shapes/constructions/pullbacks.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/images.lean
  src/category_theory/limits/shapes/regular_mono.lean
Labels: ready-to-merge

#2182 chore(category_theory/images): fix some minor problems
  src/category_theory/limits/shapes/images.lean
Labels: ready-to-merge

#2163 feat(data/finset): monotone bijection from fin k
  src/data/equiv/basic.lean
  src/data/finset.lean
  src/data/fintype.lean
  src/data/list/sort.lean
  src/group_theory/sylow.lean
Labels: ready-to-merge

#2185 docs(category_theory/limits): adding many docstrings
  src/category_theory/limits/limits.lean
Labels: ready-to-merge

#2158 feat(data/zmod): lemmas about totient and zmod
  src/data/fintype.lean
  src/data/nat/totient.lean
  src/data/zmod/basic.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/field_theory/finite.lean
Labels: ready-to-merge

#2189 feat(category_theory): some natural isomorphisms related to composition by functors
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/pempty.lean
Labels: ready-to-merge

#2180 feat(category_theory): subsingleton (has_zero_morphisms)
  src/category_theory/discrete_category.lean
  src/category_theory/limits/shapes/zero.lean
  src/tactic/ext.lean
Labels: ready-to-merge

#2188 chore(category_theory): missing simp lemmas
  src/category_theory/types.lean
Labels: ready-to-merge

#2196 chore(algebra/Module/monoidal): add the simp lemmas for unitors and associativity
  src/algebra/category/Module/basic.lean
  src/algebra/category/Module/monoidal.lean
Labels: ready-to-merge

#2192 feat(category_theory/limits): the isomorphism expressing preservation of chosen limits
  src/category_theory/limits/limits.lean
  src/category_theory/limits/preserves.lean
Labels: ready-to-merge

#2135 feat(finsupp): move convolution product to type wrapper `add_monoid_algebra`.
  src/data/finsupp.lean
  src/data/finsupp/pointwise.lean
  src/data/monoid_algebra.lean
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/linear_algebra/finsupp.lean
  src/ring_theory/polynomial.lean
  src/ring_theory/power_series.lean
Labels: ready-to-merge

#2193 feat(category_theory): unbundled functors and lax monoidal functors
  src/category_theory/functor.lean
  src/category_theory/functorial.lean
  src/category_theory/monoidal/functorial.lean
Labels: ready-to-merge

#2190 chore(category_theory): change monoidal_of_has_finite_products to use binary products
  src/category_theory/monoidal/of_has_finite_products.lean
Labels: ready-to-merge

#2200 feat(category_theory): add naturality_assoc simp lemma
  src/category_theory/natural_transformation.lean
Labels: ready-to-merge

#2203 chore(leanpkg.toml): Lean 3.7.2c
  docs/contribute/index.md
  leanpkg.toml
Labels: ready-to-merge

#2206 doc(docs/contribute/index.md): remove obsolete recommendation to use lean-3.7.2 branch
  docs/contribute/index.md
Labels: ready-to-merge

#2194 refactor(scripts/mk_nolint): produce nolints.txt file during linting
  .github/workflows/build.yml
  .gitignore
  scripts/lint_mathlib.lean
  scripts/mk_all.sh
  scripts/mk_nolint.lean
  scripts/rm_all.sh
  scripts/update_nolints.sh
  src/logic/basic.lean
  src/logic/function.lean
  src/meta/expr.lean
  src/tactic/lint.lean
  test/lint.lean
Labels: ready-to-merge

#2211 doc(ring_theory/adjoin_root): add docstring
  src/ring_theory/adjoin_root.lean
Labels: ready-to-merge

#2161 fix(linear_algebra/basic): make R explicit in linear_equiv.refl
  src/linear_algebra/basic.lean
  src/topology/algebra/module.lean
Labels: ready-to-merge

#2208 feat(ring_theory/algebra) : generalize `rat.algebra_rat` to `division_ring`
  src/algebra/commute.lean
  src/algebra/field_power.lean
  src/algebra/semiconj.lean
  src/data/padics/padic_numbers.lean
  src/data/rat/cast.lean
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#2213 chore(linear_algebra/*): rename copair, pair to coprod, prod
  archive/sensitivity.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/dimension.lean
Labels: ready-to-merge

#2201 feat(tactic/doc_commands): allow doc strings on add_tactic_doc
  docs/commands.md
  docs/contribute/doc.md
  src/algebra/category/Mon/basic.lean
  src/algebra/module.lean
  src/deprecated/group.lean
  src/group_theory/coset.lean
  src/logic/basic.lean
  src/meta/expr.lean
  src/tactic/cache.lean
  src/tactic/doc_commands.lean
  src/tactic/elide.lean
  src/tactic/ext.lean
  src/tactic/finish.lean
  src/tactic/fix_reflect_string.lean
  src/tactic/lint.lean
  src/tactic/localized.lean
  src/tactic/norm_cast.lean
  src/tactic/norm_num.lean
  test/doc_commands.lean
Labels: ready-to-merge

#2212 fix(tactic/transport): make `to_additive` copy `protected`status
  src/algebra/group/to_additive.lean
  src/algebra/group/units.lean
  src/data/complex/exponential.lean
  src/data/polynomial.lean
  src/linear_algebra/nonsingular_inverse.lean
  src/measure_theory/bochner_integration.lean
  src/measure_theory/measure_space.lean
  src/tactic/transport.lean
  src/topology/algebra/infinite_sum.lean
Labels: ready-to-merge

#2215 feat(algebra/module): `f : E →+ F` is `ℚ`-linear
  src/algebra/direct_limit.lean
  src/algebra/module.lean
Labels: ready-to-merge

#2216 chore(ring_theory/algebra): generalize restrict_scalars to noncommutative algebras
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#2120 feat(analysis/convex.cone): prove M. Riesz extension theorem, Hahn-Banach theorem
  src/algebra/module.lean
  src/analysis/convex/basic.lean
  src/analysis/convex/cone.lean
  src/analysis/normed_space/hahn_banach.lean
  src/data/set/basic.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/linear_pmap.lean
  src/order/basic.lean
  src/order/conditionally_complete_lattice.lean
Labels: ready-to-merge

#2070 refactor(topology/metric_space/contracting): redefine using emetric
  src/data/set/function.lean
  src/data/subtype.lean
  src/topology/constructions.lean
  src/topology/metric_space/contracting.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#2217 doc(data/int/gcd): attribution + module doc
  src/data/int/gcd.lean
Labels: ready-to-merge

#2229 feat(linear_algebra): add range_le_ker_iff
  src/linear_algebra/basic.lean
Labels: ready-to-merge

#2225 chore(README,docs/*): replace tactic doc files with links to mathlib docs
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  archive/README.md
  docs/commands.md
  docs/contribute/doc.md
  docs/contribute/index.md
  docs/extras/calc.md
  docs/extras/conv.md
  docs/extras/simp.md
  docs/extras/tactic_writing.md
  docs/extras/well_founded_recursion.md
  docs/holes.md
  docs/tactics.md
  docs/theories/category_theory.md
  src/category_theory/category/default.lean
Labels: ready-to-merge

#2205 feat(data/equiv): sigma_congr
  src/data/equiv/basic.lean
Labels: ready-to-merge

#2227 feat(tactic/show_term): show_term { t } prints the term constructed by t
  src/tactic/basic.lean
  src/tactic/show_term.lean
Labels: ready-to-merge

#2221 feat(tactic/conv/apply_congr): using congruence lemmas inside conv
  src/tactic/basic.lean
  src/tactic/converter/apply_congr.lean
  src/tactic/converter/interactive.lean
  src/tactic/doc_commands.lean
  test/conv/apply_congr.lean
Labels: ready-to-merge

#2209 feat(tactic/core): trace_if_enabled
  src/tactic/chain.lean
  src/tactic/core.lean
  src/tactic/finish.lean
  src/tactic/suggest.lean
Labels: ready-to-merge

#2226 chore(algebra/ordered_field): merge `inv_pos` / `zero_lt_inv` with `inv_pos'` / `inv_neg`
  src/algebra/archimedean.lean
  src/algebra/ordered_field.lean
  src/analysis/calculus/mean_value.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/complex/exponential.lean
  src/analysis/convex/basic.lean
  src/analysis/convex/cone.lean
  src/analysis/normed_space/multilinear.lean
  src/analysis/normed_space/operator_norm.lean
  src/analysis/specific_limits.lean
  src/data/complex/exponential.lean
  src/data/rat/cast.lean
  src/data/real/basic.lean
  src/data/real/hyperreal.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/gromov_hausdorff.lean
Labels: ready-to-merge

#2238 chore(README): add Bryan; alphabetize
  README.md
Labels: ready-to-merge

#2204 feat(data/equiv): pi_congr
  src/data/equiv/basic.lean
Labels: ready-to-merge

#2230 feat(*): a few more theorems about `unique` and `subsingleton`
  src/data/equiv/basic.lean
  src/data/set/basic.lean
  src/logic/unique.lean
  src/topology/basic.lean
  src/topology/metric_space/antilipschitz.lean
Labels: ready-to-merge

#2231 feat(topology/local_homeomorph): a few facts about `local_homeomorph`
  src/analysis/asymptotics.lean
  src/topology/local_homeomorph.lean
Labels: ready-to-merge

#2234 feat(topology/metric_space/isometry): add_left/right, neg
  src/topology/metric_space/isometry.lean
Labels: ready-to-merge

#2174 feat(algebra/homology): chain complexes
  src/algebra/homology/chain_complex.lean
  src/algebra/homology/homology.lean
  src/category_theory/concrete_category/basic.lean
  src/category_theory/differential_object.lean
  src/category_theory/equivalence.lean
  src/category_theory/graded_object.lean
  src/category_theory/limits/shapes/zero.lean
  src/category_theory/shift.lean
Labels: ready-to-merge

#2237 chore(ci): only run on push
  .github/workflows/build.yml
  docs/contribute/index.md
Labels: ready-to-merge

#2222 chore(tactic/solve_by_elim): refactor
  src/set_theory/pgame.lean
  src/tactic/core.lean
  src/tactic/monotonicity/interactive.lean
  src/tactic/solve_by_elim.lean
  test/solve_by_elim.lean
Labels: ready-to-merge

#2218 feat(tactic/squeeze): improve suggestion of `cases x; squeeze_simp`
  src/meta/expr.lean
  src/tactic/core.lean
  src/tactic/squeeze.lean
  test/examples.lean
  test/packaged_goal.lean
Labels: ready-to-merge

#2241 feat(data/equiv/functor): bifunctor.map_equiv
  src/data/equiv/functor.lean
  src/ring_theory/free_comm_ring.lean
Labels: ready-to-merge

#2243 refactor(data/set/function): move `function.restrict` to `set`, redefine
  archive/sensitivity.lean
  src/analysis/complex/exponential.lean
  src/data/set/basic.lean
  src/data/set/countable.lean
  src/data/set/function.lean
  src/data/subtype.lean
  src/linear_algebra/basis.lean
  src/logic/function.lean
  src/measure_theory/integration.lean
  src/topology/constructions.lean
  src/topology/continuous_on.lean
  src/topology/metric_space/antilipschitz.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/contracting.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#2247 feat(topology/algebra/module): define `fst` and `snd`, review
  src/geometry/manifold/mfderiv.lean
  src/topology/algebra/module.lean
Labels: ready-to-merge

#2232 feat(data/equiv/local_equiv): construct from `bij_on` or `inj_on`
  src/data/equiv/local_equiv.lean
  src/data/set/function.lean
Labels: ready-to-merge

#2244 doc(docs/install/project.md): mention that projects are git repositories
  docs/install/project.md
Labels: ready-to-merge

#2248 chore(.mergify.yml): cleanup
  .mergify.yml
Labels: ready-to-merge

#2252 run lint+tests if build step succeeds (see #2250)
  .github/workflows/build.yml
Labels: ready-to-merge

#2250 chore(ci): update nolints before docs and leanchecker
  .github/workflows/build.yml
Labels: ready-to-merge

#2224 chore(tactic/*): update tags
  src/tactic/cache.lean
  src/tactic/core.lean
  src/tactic/elide.lean
  src/tactic/ext.lean
  src/tactic/finish.lean
  src/tactic/hint.lean
  src/tactic/interactive.lean
  src/tactic/linarith.lean
  src/tactic/localized.lean
  src/tactic/norm_cast.lean
  src/tactic/omega/main.lean
  src/tactic/pi_instances.lean
  src/tactic/replacer.lean
  src/tactic/restate_axiom.lean
  src/tactic/ring.lean
  src/tactic/ring_exp.lean
  src/tactic/solve_by_elim.lean
  src/tactic/tidy.lean
Labels: ready-to-merge

#2253 chore(tactic/lint): typo
  src/tactic/lint.lean
Labels: ready-to-merge

#2254 feat(logic/basic): trivial transport lemmas
  src/category_theory/limits/shapes/equalizers.lean
  src/data/nat/basic.lean
  src/logic/basic.lean
Labels: ready-to-merge

#2223 feat(algebra/ring): generalize mul_ite
  src/algebra/big_operators.lean
  src/algebra/group_power.lean
  src/algebra/ring.lean
  src/analysis/convex/basic.lean
  src/analysis/convex/specific_functions.lean
  src/data/equiv/basic.lean
  src/data/nat/cast.lean
  src/data/nat/multiplicity.lean
  src/data/zmod/quadratic_reciprocity.lean
  src/linear_algebra/nonsingular_inverse.lean
Labels: ready-to-merge

#2257 chore(data/int/basic): change instance order
  src/data/int/basic.lean
Labels: ready-to-merge

#2263 chore(scripts/deploy_docs.sh): skip gen_docs if already built
  scripts/deploy_docs.sh
Labels: ready-to-merge

#2233 feat(analysis/normed_space/operator_norm): a few more estimates
  src/analysis/normed_space/operator_norm.lean
  src/topology/metric_space/antilipschitz.lean
Labels: ready-to-merge

#2262 fix(tactic/squeeze): do not fail when closing the goal (#2261)
  src/tactic/squeeze.lean
  test/examples.lean
Labels: ready-to-merge

#2256 chore(data/equiv/basic): simp to_fun to coe
  src/data/equiv/basic.lean
  src/topology/metric_space/gromov_hausdorff.lean
Labels: ready-to-merge

#2264 fix(scripts/deploy_docs.sh): cd before git log
  scripts/deploy_docs.sh
Labels: ready-to-merge
