Repository leanprover-community/mathlib, pull requests merged in 2020-02, with the labels that each got.

#1935 fix(data/nat/basic): make arguments to `choose_succ_right_eq` explicit
  src/data/nat/basic.lean
Labels: ready-to-merge

#1938 feat(algebra/group/units): add units.coe_mk_of_mul_eq_one
  src/algebra/group/units.lean
Labels: ready-to-merge

#1936 feat(data/nat/basic): two identities for `choose`
  src/data/nat/basic.lean
Labels: ready-to-merge

#1937 feat(data/fintype): range_prod_eq_univ_prod
  src/data/fintype.lean
Labels: ready-to-merge

#1940 chore(data/subtype): fix `∀` vs `Π`
  src/data/subtype.lean
Labels: ready-to-merge

#1939 feat(data/set/basic): define `set.subsingleton`
  src/data/finset.lean
  src/data/set/basic.lean
  src/order/filter/bases.lean
Labels: ready-to-merge

#1925 feat(algebra/pointwise): pointwise scalar-multiplication lemmas
  src/algebra/pointwise.lean
  src/analysis/convex/basic.lean
  src/analysis/convex/topology.lean
Labels: ready-to-merge

#1941 refactor(topology/metric_space/emetric_space): redefine `diam`
  src/analysis/convex/topology.lean
  src/data/real/ennreal.lean
  src/data/set/basic.lean
  src/order/bounded_lattice.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/isometry.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#1943 chore(*): rename `filter.inhabited_of_mem_sets` to `nonempty_of_mem_sets`
  src/analysis/calculus/mean_value.lean
  src/order/filter/bases.lean
  src/order/filter/basic.lean
  src/order/liminf_limsup.lean
  src/topology/algebra/ordered.lean
  src/topology/dense_embedding.lean
  src/topology/metric_space/basic.lean
  src/topology/order.lean
  src/topology/uniform_space/cauchy.lean
  src/topology/uniform_space/completion.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#1921 refactor(linear_algebra/multilinear): cleanup of multilinear maps
  src/algebra/big_operators.lean
  src/analysis/complex/basic.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/bounded_linear_maps.lean
  src/analysis/normed_space/operator_norm.lean
  src/data/finset.lean
  src/linear_algebra/multilinear.lean
  src/measure_theory/bochner_integration.lean
  src/topology/constructions.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#1945 feat(ring_theory/power_series): several simp lemmas
  src/data/finsupp.lean
  src/data/mv_polynomial.lean
  src/data/polynomial.lean
  src/ring_theory/power_series.lean
Labels: ready-to-merge

#1947 feat(tactic/lint): Three new linters, update illegal_constants
  docs/commands.md
  scripts/mk_all.sh
  scripts/mk_nolint.lean
  src/algebra/lie_algebra.lean
  src/category/monad/writer.lean
  src/category_theory/adjunction/limits.lean
  src/category_theory/concrete_category/bundled_hom.lean
  src/data/list/defs.lean
  src/meta/expr.lean
  src/order/filter/filter_product.lean
  src/order/fixed_points.lean
  src/order/pilex.lean
  src/ring_theory/ideal_operations.lean
  src/tactic/core.lean
  src/tactic/lint.lean
  src/topology/algebra/uniform_ring.lean
  test/expr.lean
  test/lint.lean
Labels: ready-to-merge

#1952 feat(number_theory/bernoulli): Add definition of Bernoulli numbers
  src/number_theory/bernoulli.lean
Labels: ready-to-merge

#1948 feat(topology/algebra/multilinear): define continuous multilinear maps
  src/linear_algebra/multilinear.lean
  src/topology/algebra/multilinear.lean
Labels: ready-to-merge

#1949 feat(data/set/intervals): define intervals and prove basic properties
  src/algebra/order_functions.lean
  src/analysis/convex/basic.lean
  src/data/indicator_function.lean
  src/data/set/intervals/basic.lean
  src/data/set/intervals/default.lean
  src/data/set/intervals/unordered_interval.lean
  src/measure_theory/borel_space.lean
  src/measure_theory/lebesgue_measure.lean
  src/order/bounds.lean
Labels: ready-to-merge

#1958 chore(*): bump Lean version to 3.5.1c
  .github/workflows/build.yml
  .mergify.yml
  docs/contribute/index.md
  leanpkg.toml
  scripts/deploy_nightly.sh
  src/algebra/ring.lean
  src/tactic/squeeze.lean
Labels: ready-to-merge

#1916 feat(tactic/rename): Add improved renaming tactic
  docs/tactics.md
  src/data/list/defs.lean
  src/tactic/basic.lean
  src/tactic/rename.lean
  test/tactics.lean
Labels: ready-to-merge

#1950 refactor(measure_theory/set_integral): move set integral into namespace set and add some lemmas
  src/measure_theory/bochner_integration.lean
  src/measure_theory/set_integral.lean
Labels: ready-to-merge

#1962 chore(tactic/basic,default): add missing tactics
  src/tactic/basic.lean
  src/tactic/default.lean
Labels: ready-to-merge

#1965 feat(*): a few simple lemmas
  src/data/set/basic.lean
  src/order/complete_lattice.lean
  src/order/filter/basic.lean
  src/topology/algebra/ordered.lean
Labels: ready-to-merge

#1966 chore(topology/metric_space/basic): simplify `tendsto_nhds`
  src/analysis/normed_space/basic.lean
  src/topology/bounded_continuous_function.lean
  src/topology/metric_space/basic.lean
Labels: ready-to-merge

#1967 refactor(topology/basic): rewrite some proofs using filter bases
  src/topology/basic.lean
  src/topology/bounded_continuous_function.lean
  src/topology/order.lean
Labels: ready-to-merge

#1968 refactor(topology/continuous_on): use filter bases
  src/topology/continuous_on.lean
Labels: ready-to-merge

#1957 feat(algebraic_geometry/prime_spectrum): first definitions
  src/algebraic_geometry/prime_spectrum.lean
  src/topology/basic.lean
Labels: ready-to-merge

#1956 feat(analysis/normed_space/multilinear): norm on continuous multilinear maps
  src/analysis/normed_space/multilinear.lean
Labels: ready-to-merge

#1960 feat(linear_algebra): The Special linear group SL(n, R)
  src/algebra/module.lean
  src/data/fintype.lean
  src/data/matrix/basic.lean
  src/linear_algebra/determinant.lean
  src/linear_algebra/dual.lean
  src/linear_algebra/matrix.lean
  src/linear_algebra/nonsingular_inverse.lean
  src/linear_algebra/special_linear_group.lean
Labels: ready-to-merge

#1964 refactor(topology/*): irreducible and connected sets are nonempty
  src/topology/algebra/ordered.lean
  src/topology/basic.lean
  src/topology/subset_properties.lean
Labels: ready-to-merge

#1959 refactor(data/matrix,linear_algebra): Use `matrix.mul` as default multiplication in matrix lemmas
  src/data/matrix/basic.lean
  src/data/matrix/pequiv.lean
  src/linear_algebra/determinant.lean
Labels: ready-to-merge

#1969 refactor(topology/metric_space): introduce&use `edist`/`dist` bases
  src/analysis/asymptotics.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/normed_space/banach.lean
  src/analysis/normed_space/basic.lean
  src/order/filter/bases.lean
  src/topology/algebra/infinite_sum.lean
  src/topology/bounded_continuous_function.lean
  src/topology/instances/ennreal.lean
  src/topology/metric_space/baire.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/closeds.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/hausdorff_distance.lean
  src/topology/metric_space/isometry.lean
  src/topology/uniform_space/basic.lean
  src/topology/uniform_space/cauchy.lean
Labels: ready-to-merge

#1970 feat(topology/subset_properties): alternative definitions of irreducible and connected
  src/topology/subset_properties.lean
Labels: ready-to-merge

#1971 feat(tactic/lint): check if inhabited instances should be nonempty
  scripts/mk_all.sh
  scripts/mk_nolint.lean
  src/data/list/basic.lean
  src/data/set/basic.lean
  src/data/set/countable.lean
  src/data/set/lattice.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/finsupp.lean
  src/logic/basic.lean
  src/logic/function.lean
  src/measure_theory/integration.lean
  src/order/filter/basic.lean
  src/tactic/interactive.lean
  src/tactic/lint.lean
  src/topology/basic.lean
  src/topology/instances/ennreal.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/separation.lean
  src/topology/uniform_space/cauchy.lean
Labels: ready-to-merge

#1976 chore(scripts): update nolints
  scripts/nolints.txt
Labels: ready-to-merge

#1975 chore(ci): don't build with Lean nightly
  .github/workflows/build.yml
Labels: RFC, ready-to-merge

#1981 refactor(group_theory/submonoid): redefine `subtype.monoid` manually
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
  src/ring_theory/integral_closure.lean
  src/ring_theory/subring.lean
Labels: ready-to-merge

#1977 feat(calculus/fderiv): invariance of fderiv under linear equivs
  src/analysis/calculus/fderiv.lean
  src/analysis/normed_space/basic.lean
  src/linear_algebra/basic.lean
  src/topology/algebra/module.lean
  src/topology/continuous_on.lean
  src/topology/homeomorph.lean
Labels: ready-to-merge

#1934 refactor(data/set/function): use dot notation, rename and add some lemmas
  src/data/equiv/local_equiv.lean
  src/data/finsupp.lean
  src/data/set/basic.lean
  src/data/set/countable.lean
  src/data/set/finite.lean
  src/data/set/function.lean
  src/data/subtype.lean
  src/linear_algebra/basis.lean
  src/topology/continuous_on.lean
  src/topology/metric_space/closeds.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#1982 chore(group_theory/sub*) : rename type vars
  src/group_theory/subgroup.lean
  src/group_theory/submonoid.lean
Labels: ready-to-merge

#1984 chore(category_theory/conj): avoid `is_mul_hom`
  src/category_theory/conj.lean
Labels: ready-to-merge

#1986 fix(scripts/deploy_docs): remove last trace of nightly builds
  scripts/deploy_docs.sh
Labels: ready-to-merge

#1979 feat(ci): update nolints.txt after master builds
  .github/workflows/build.yml
  scripts/update_nolints.sh
Labels: ready-to-merge

#1989 chore(algebra/group/basic): rename type vars
  src/algebra/group/basic.lean
Labels: ready-to-merge

#1955 feat(tactic/hint): try out a customisable list of tactics, and report which ones make progress
  docs/tactics.md
  src/tactic/basic.lean
  src/tactic/core.lean
  src/tactic/finish.lean
  src/tactic/hint.lean
  src/tactic/linarith.lean
  src/tactic/norm_num.lean
  src/tactic/omega/main.lean
  src/tactic/ring.lean
  src/tactic/split_ifs.lean
  src/tactic/tauto.lean
  src/tactic/tidy.lean
  test/hint.lean
Labels: ready-to-merge

#1994 chore(algebra/group/hom): add a missing `simp` lemma
  src/algebra/group/hom.lean
Labels: ready-to-merge

#2001 chore(topology/sequences): use filter bases, minor fixes
  src/topology/sequences.lean
Labels: ready-to-merge

#2000 doc(topology/metric_space/basic): add 1 docstring
  src/topology/metric_space/basic.lean
Labels: ready-to-merge

#1996 feat(ring_theory/algebra): add ext_iff
  src/ring_theory/algebra.lean
Labels: ready-to-merge

#1997 chore(algebra/group_power): rename type vars, minor cleanup
  src/algebra/group/type_tags.lean
  src/algebra/group_power.lean
  src/algebra/lie_algebra.lean
  src/analysis/complex/exponential.lean
  src/category_theory/conj.lean
  src/group_theory/quotient_group.lean
Labels: ready-to-merge

#2002 chore(analysis/calculus/tangent_cone): simplify a proof
  src/analysis/calculus/tangent_cone.lean
Labels: ready-to-merge

#1990 add "Try this: " to squeeze_simp and suggest
  docs/tactics.md
  src/tactic/hint.lean
  src/tactic/rcases.lean
  src/tactic/squeeze.lean
  src/tactic/suggest.lean
  src/tactic/tidy.lean
  test/suggest.lean
  test/tidy.lean
Labels: ready-to-merge

#1974 feat(tactic/rename_var): A teaching tactic
  docs/tactics.md
  src/tactic/basic.lean
  src/tactic/rename_var.lean
  test/rename_var.lean
Labels: ready-to-merge

#2003 feat(data/set/intervals): add `Ici_subset_Ici`, `Iic_subset_Iic`
  src/data/set/intervals/basic.lean
Labels: ready-to-merge

#2005 chore(set_theory/ordinal): shorten proofs
  src/set_theory/ordinal.lean
Labels: ready-to-merge

#2006 chore(*): reduce proof size
  src/data/dfinsupp.lean
  src/measure_theory/ae_eq_fun.lean
Labels: ready-to-merge

#1999 refactor(algebra/field): partially migrate to bundled homs
  src/algebra/field.lean
  src/algebra/field_power.lean
  src/field_theory/subfield.lean
Labels: ready-to-merge

#1980 refactor(topology/subset_properties): use finite subcovers indexed by types
  src/topology/metric_space/basic.lean
  src/topology/subset_properties.lean
Labels: ready-to-merge

#1973 feat(linear_algebra/contraction): define contraction maps between a module and its dual
  src/group_theory/group_action.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/contraction.lean
Labels: ready-to-merge

#1978 feat(data/fin): init and snoc
  src/data/fin.lean
  src/data/fintype.lean
  src/logic/function.lean
Labels: ready-to-merge

#2007 refactor(topology/maps): split the proof of `is_open_map_iff_nhds_le`
  src/topology/maps.lean
Labels: ready-to-merge

#2008 chore(topology/constructions): rename `tendsto_prod_mk_nhds`
  src/analysis/calculus/tangent_cone.lean
  src/analysis/normed_space/basic.lean
  src/topology/algebra/module.lean
  src/topology/algebra/monoid.lean
  src/topology/constructions.lean
  src/topology/continuous_on.lean
  src/topology/instances/ennreal.lean
Labels: ready-to-merge

#2009 feat(scripts/deploy_nightly): change pre-release to release
  scripts/deploy_nightly.sh
Labels: ready-to-merge

#2011 chore(analysis/normed_space/basic): implicit args
  src/analysis/asymptotics.lean
  src/analysis/calculus/deriv.lean
  src/analysis/calculus/fderiv.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/normed_space/banach.lean
  src/analysis/normed_space/basic.lean
  src/analysis/normed_space/multilinear.lean
  src/analysis/normed_space/operator_norm.lean
  src/analysis/specific_limits.lean
  src/data/padics/hensel.lean
  src/data/padics/padic_numbers.lean
  src/measure_theory/simple_func_dense.lean
  src/topology/metric_space/cau_seq_filter.lean
Labels: ready-to-merge

#1914 feat(roadmap): add some formal roadmaps in topology
  roadmap/todo.lean
  roadmap/topology/paracompact.lean
  roadmap/topology/shrinking_lemma.lean
Labels: ready-to-merge

#2010 feat(docs): install mathlibtools package with pip
  docs/contribute/index.md
  docs/install/debian_details.md
  docs/install/linux.md
  docs/install/macos.md
  docs/install/windows.md
Labels: ready-to-merge

#2014 chore(measure_theory/*): make a few proofs slightly shorter
  src/measure_theory/bochner_integration.lean
  src/measure_theory/l1_space.lean
  src/measure_theory/simple_func_dense.lean
Labels: ready-to-merge

#2015 refactor(algebra/associated): move `is_unit` def to `algebra/group`
  src/algebra/associated.lean
  src/algebra/group/default.lean
  src/algebra/group/is_unit.lean
  src/algebra/group/units.lean
Labels: ready-to-merge

#2013 refactor(analysis/calculus/tangent_cone): split a proof into parts
  src/algebra/associated.lean
  src/algebra/module.lean
  src/analysis/calculus/tangent_cone.lean
  src/analysis/normed_space/basic.lean
  src/topology/algebra/module.lean
Labels: ready-to-merge

#1836 feat(analysis/mean_inequalities) : Prove AM-GM
  src/analysis/calculus/deriv.lean
  src/analysis/convex/specific_functions.lean
  src/analysis/mean_inequalities.lean
  src/data/nat/parity.lean
  src/data/real/nnreal.lean
  src/data/set/intervals/basic.lean
  src/topology/algebra/ordered.lean
Labels: ready-to-merge

#2019 fix(tactic/tauto): fix typos
  docs/tactics.md
  src/tactic/tauto.lean
Labels: ready-to-merge

#2020 feat(algebra/group): add `units.lift_right` and `is_unit.lift_right`
  src/algebra/group/is_unit.lean
  src/algebra/group/units_hom.lean
Labels: ready-to-merge

#2022 chore(ci): check roadmap directory
  .github/workflows/build.yml
  roadmap/topology/paracompact.lean
  roadmap/topology/shrinking_lemma.lean
Labels: ready-to-merge

#2023 doc(lint): add linter missing from list of defaults
  docs/commands.md
  src/tactic/lint.lean
Labels: ready-to-merge

#2025 feat(data/int/basic): format -42 as -42 instead of -(41+1)
  src/data/int/basic.lean
Labels: ready-to-merge

#2027 fix(data/bool): remove simp attribute from commutativity lemmas
  src/data/bool.lean
  src/data/int/basic.lean
Labels: ready-to-merge

#2026 fix(*): remove loopy simp lemmas
  src/data/equiv/basic.lean
  src/order/basic.lean
Labels: ready-to-merge

#1985 refactor(*/multilinear): better right curryfication
  src/analysis/normed_space/multilinear.lean
  src/linear_algebra/multilinear.lean
  src/topology/algebra/multilinear.lean
Labels: ready-to-merge

#2024 feat(tactic/hint): update tactic list
  src/tactic/hint.lean
  src/tactic/norm_cast.lean
  test/hint.lean
  test/tidy.lean
Labels: ready-to-merge

#1972 feat(algebraic_geometry/prime_spectrum): vanishing ideal
  src/algebraic_geometry/prime_spectrum.lean
Labels: ready-to-merge

#2017 feat(tactic/lint): check that left-hand side of all simp lemmas is in simp-normal form
  docs/commands.md
  scripts/mk_all.sh
  src/algebra/big_operators.lean
  src/algebra/field.lean
  src/algebra/group_power.lean
  src/algebra/ring.lean
  src/algebraic_geometry/prime_spectrum.lean
  src/analysis/normed_space/multilinear.lean
  src/category_theory/const.lean
  src/category_theory/equivalence.lean
  src/category_theory/functor.lean
  src/category_theory/functor_category.lean
  src/category_theory/isomorphism.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/shapes/binary_products.lean
  src/category_theory/limits/shapes/pullbacks.lean
  src/category_theory/natural_isomorphism.lean
  src/category_theory/natural_transformation.lean
  src/data/equiv/denumerable.lean
  src/data/fin.lean
  src/data/finset.lean
  src/data/int/basic.lean
  src/data/int/parity.lean
  src/data/list/alist.lean
  src/data/list/basic.lean
  src/data/list/sigma.lean
  src/data/multiset.lean
  src/data/mv_polynomial.lean
  src/data/option/basic.lean
  src/data/set/basic.lean
  src/data/set/lattice.lean
  src/data/zsqrtd/basic.lean
  src/measure_theory/l1_space.lean
  src/measure_theory/set_integral.lean
  src/order/complete_lattice.lean
  src/order/filter/filter_product.lean
  src/ring_theory/localization.lean
  src/ring_theory/power_series.lean
  src/set_theory/ordinal.lean
  src/set_theory/zfc.lean
  src/tactic/core.lean
  src/tactic/lint.lean
  src/topology/algebra/module.lean
  src/topology/local_homeomorph.lean
  src/topology/metric_space/basic.lean
  test/lint_simp_nf.lean
Labels: ready-to-merge

#1953 feat(tactic): add various tactics about local definitions
  src/data/option/defs.lean
  src/tactic/core.lean
  src/tactic/interactive.lean
  src/tactic/monotonicity/interactive.lean
  test/tactics.lean
Labels: ready-to-merge

#2034 chore(topology/metric_space/emetric_space): use filter bases in 2 proofs
  src/topology/metric_space/emetric_space.lean
Labels: ready-to-merge

#1617 chore(presheafed_space): avoid deterministic timeout
  src/algebraic_geometry/presheafed_space.lean
  src/algebraic_geometry/stalks.lean
Labels: ready-to-merge, request-review

#1998 feat(category_theory/limits) Binary product from pullbacks and terminal object
  src/category_theory/discrete_category.lean
  src/category_theory/equivalence.lean
  src/category_theory/limits/shapes/constructions/binary_products.lean
Labels: ready-to-merge

#1988 feat(category_theory/limits): kernels
  docs/references.bib
  src/algebra/category/Module/basic.lean
  src/category_theory/limits/limits.lean
  src/category_theory/limits/shapes/equalizers.lean
  src/category_theory/limits/shapes/kernels.lean
  src/category_theory/limits/shapes/terminal.lean
  src/category_theory/limits/shapes/zero.lean
Labels: ready-to-merge

#2036 feat(*): misc simple lemmas
  src/analysis/normed_space/basic.lean
  src/data/set/basic.lean
  src/order/filter/basic.lean
  src/topology/metric_space/emetric_space.lean
Labels: ready-to-merge

#2039 feat(ci): skip Azure upload if archive already exists
  .github/workflows/build.yml
Labels: ready-to-merge

#1987 feat(algebraic_geometry/prime_spectrum): prime spectrum of a ring is compact
  src/algebraic_geometry/prime_spectrum.lean
  src/linear_algebra/basic.lean
  src/linear_algebra/finsupp.lean
  src/order/complete_lattice.lean
Labels: ready-to-merge

#2035 refactor(topology/metric_space/lipschitz): redefine for an `emetric_space`
  src/analysis/ODE/gronwall.lean
  src/analysis/normed_space/finite_dimension.lean
  src/analysis/normed_space/operator_norm.lean
  src/data/real/ennreal.lean
  src/topology/bounded_continuous_function.lean
  src/topology/metric_space/closeds.lean
  src/topology/metric_space/contracting.lean
  src/topology/metric_space/gromov_hausdorff.lean
  src/topology/metric_space/gromov_hausdorff_realized.lean
  src/topology/metric_space/hausdorff_distance.lean
  src/topology/metric_space/lipschitz.lean
Labels: ready-to-merge

#2043 chore(test): don't use sorry in tests, to reduce noise
  test/apply.lean
  test/tactics.lean
Labels: ready-to-merge

#2042 chore(*): minimise imports of data.list.basic
  src/algebra/group_power.lean
  src/category/fold.lean
  src/data/array/lemmas.lean
  src/data/int/basic.lean
  src/data/nat/prime.lean
  src/data/seq/wseq.lean
  src/group_theory/free_group.lean
  src/tactic/linarith.lean
  src/tactic/omega/coeffs.lean
  test/monotonicity.lean
Labels: ready-to-merge

#2037 feat(topology): an `is_complete` set is a `complete_space`
  src/analysis/normed_space/finite_dimension.lean
  src/topology/metric_space/closeds.lean
  src/topology/opens.lean
  src/topology/uniform_space/cauchy.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#1991 docs(data/set/basic): add module docstring
  src/data/set/basic.lean
Labels: ready-to-merge

#2041 feat(tactic/lint): support @[nolint unused_arguments]
  docs/commands.md
  scripts/mk_all.sh
  scripts/mk_nolint.lean
  scripts/nolints.txt
  src/category/functor.lean
  src/category/monad/writer.lean
  src/category_theory/concrete_category/bundled_hom.lean
  src/meta/expr.lean
  src/meta/rb_map.lean
  src/number_theory/pell.lean
  src/order/filter/bases.lean
  src/order/filter/basic.lean
  src/order/lattice.lean
  src/ring_theory/algebra.lean
  src/ring_theory/localization.lean
  src/set_theory/ordinal.lean
  src/tactic/core.lean
  src/tactic/interactive.lean
  src/tactic/linarith.lean
  src/tactic/lint.lean
  src/topology/algebra/ordered.lean
  src/topology/metric_space/basic.lean
  src/topology/metric_space/emetric_space.lean
  src/topology/topological_fiber_bundle.lean
  src/topology/uniform_space/cauchy.lean
  test/lint.lean
Labels: ready-to-merge

#2046 doc(category_theory): add a few docstrings
  src/category_theory/core.lean
  src/category_theory/isomorphism.lean
Labels: ready-to-merge

#2038 feat(tactic/lint): add linter for simp lemmas whose lhs has a variable as head symbol
  docs/commands.md
  src/algebra/field.lean
  src/algebra/module.lean
  src/data/list/basic.lean
  src/tactic/lint.lean
  test/lint_simp_var_head.lean
Labels: ready-to-merge

#2051 refactor(topology/metric_space/isometry): remove isometry_inv_fun from isometric
  src/topology/metric_space/isometry.lean
Labels: ready-to-merge

#2050 refactor(order/copy): move complete_lattice.copy to its own file
  src/data/setoid.lean
  src/order/copy.lean
  src/order/filter/basic.lean
  src/topology/opens.lean
Labels: ready-to-merge

#2044 chore(data/fintype): move results depending on big_operators
  src/algebra/big_operators.lean
  src/analysis/normed_space/multilinear.lean
  src/data/fintype.lean
  src/data/fintype/card.lean
  src/data/set/finite.lean
  src/group_theory/perm/sign.lean
  src/group_theory/sylow.lean
  src/linear_algebra/basis.lean
  src/linear_algebra/determinant.lean
  src/number_theory/bernoulli.lean
  src/set_theory/cardinal.lean
Labels: ready-to-merge

#2040 chore(category_theory/limits): unify naming of lemmas related to the (co)lim functor
  src/algebraic_geometry/stalks.lean
  src/category_theory/limits/limits.lean
  src/topology/sheaves/stalks.lean
Labels: ready-to-merge

#2028 refactor(order/bounds): use dot notation, reorder, prove more properties
  src/data/set/finite.lean
  src/data/set/lattice.lean
  src/order/basic.lean
  src/order/bounds.lean
  src/order/complete_boolean_algebra.lean
  src/order/complete_lattice.lean
  src/order/conditionally_complete_lattice.lean
  src/order/galois_connection.lean
  src/topology/algebra/ordered.lean
  src/topology/instances/ennreal.lean
Labels: ready-to-merge

#2045 feat(tactic/lint): linter for commutativity lemmas that are marked simp
  docs/commands.md
  src/data/finmap.lean
  src/data/finset.lean
  src/data/hash_map.lean
  src/data/list/alist.lean
  src/data/list/basic.lean
  src/data/multiset.lean
  src/data/nat/dist.lean
  src/linear_algebra/basis.lean
  src/tactic/lint.lean
  src/topology/algebra/infinite_sum.lean
  test/lint_simp_comm.lean
Labels: ready-to-merge

#2053 chore(analyis/normed_space/banach): split proof to avoid timeout
  src/analysis/normed_space/banach.lean
Labels: ready-to-merge

#2054 chore(field_theory/minimal_polynomial): fix timeout
  src/field_theory/minimal_polynomial.lean
Labels: ready-to-merge

#2057 chore(data/list/basic): drop `append_foldl` and `append_foldr`, add `map_nil` and `prod_singleton`
  src/data/list/basic.lean
Labels: ready-to-merge

#2058 chore(data/prod): rename `injective_prod` to `injective.prod`
  src/data/prod.lean
  src/topology/uniform_space/uniform_embedding.lean
Labels: ready-to-merge

#2021 feat(ring_theory/polynomial): mv_polynomial.integral_domain
  src/algebra/ring.lean
  src/data/equiv/algebra.lean
  src/data/equiv/fin.lean
  src/data/mv_polynomial.lean
  src/ring_theory/adjoin.lean
  src/ring_theory/polynomial.lean
Labels: ready-to-merge

#2059 doc(data/finsupp): module docs and docstrings
  src/data/finsupp.lean
Labels: ready-to-merge

#2063 feat(tactic/tidy): include norm_cast in tidy
  src/tactic/auto_cases.lean
  src/tactic/core.lean
  src/tactic/hint.lean
  src/tactic/tidy.lean
Labels: ready-to-merge

#2048 feat(ci): avoid push to Azure if branch has been updated
  .github/workflows/build.yml
  scripts/deploy_nightly.sh
  scripts/update_nolints.sh
Labels: ready-to-merge

#2012 refactor(analysis/calculus/times_cont_diff): massive refactor
  src/algebra/ordered_ring.lean
  src/analysis/calculus/times_cont_diff.lean
  src/analysis/normed_space/bounded_linear_maps.lean
  src/analysis/normed_space/multilinear.lean
  src/geometry/manifold/basic_smooth_bundle.lean
  src/geometry/manifold/mfderiv.lean
  src/geometry/manifold/real_instances.lean
  src/geometry/manifold/smooth_manifold_with_corners.lean
  src/linear_algebra/multilinear.lean
  src/topology/algebra/multilinear.lean
  src/topology/continuous_on.lean
Labels: ready-to-merge

#1557 fix(tactic/ring): more precise pattern match for div
  src/algebra/quadratic_discriminant.lean
  src/linear_algebra/determinant.lean
  src/tactic/norm_num.lean
  src/tactic/ring.lean
  test/ring.lean
Labels: ready-to-merge

#2062 feat(ring_theory): Fractional ideals
  src/ring_theory/algebra_operations.lean
  src/ring_theory/fractional_ideal.lean
  src/ring_theory/localization.lean
Labels: ready-to-merge

#2065 chore(ci): remove unneeded Lean version restrictions
  .github/workflows/build.yml
  scripts/deploy_docs.sh
  scripts/deploy_nightly.sh
Labels: ready-to-merge
